/**
 * Motivational quotes bundled with the app (cleaned from the user-provided
 * dataset: duplicate quotes removed, the duplicate "Appendix" category
 * dropped). Used by the Quotes notification feature and the Quote widget.
 */

export const QUOTE_CATEGORIES = [
  { id: 'motivation', label: { en: 'Motivation', ar: 'التحفيز' } },
  { id: 'discipline', label: { en: 'Discipline', ar: 'الانضباط' } },
  { id: 'success', label: { en: 'Success', ar: 'النجاح' } },
  { id: 'mindset', label: { en: 'Mindset', ar: 'العقلية' } },
  { id: 'self_development', label: { en: 'Self-Development', ar: 'تطوير الذات' } },
  { id: 'life_wisdom', label: { en: 'Life Wisdom', ar: 'حكمة الحياة' } },
];

export const QUOTES = [
  { id: 1, text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs', category: 'motivation' },
  { id: 2, text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius', category: 'motivation' },
  { id: 3, text: 'The future belongs to those who believe in the beauty of their dreams.', author: 'Eleanor Roosevelt', category: 'motivation' },
  { id: 4, text: 'The only impossible journey is the one you never begin.', author: 'Tony Robbins', category: 'motivation' },
  { id: 5, text: 'Don\'t watch the clock; do what it does. Keep going.', author: 'Sam Levenson', category: 'motivation' },
  { id: 6, text: 'It always seems impossible until it\'s done.', author: 'Nelson Mandela', category: 'motivation' },
  { id: 7, text: 'The secret of getting ahead is getting started.', author: 'Mark Twain', category: 'motivation' },
  { id: 8, text: 'You are never too old to set another goal or to dream a new dream.', author: 'C.S. Lewis', category: 'motivation' },
  { id: 9, text: 'The harder you work for something, the greater you\'ll feel when you achieve it.', author: 'Unknown', category: 'motivation' },
  { id: 10, text: 'Dream bigger. Do bigger.', author: 'Unknown', category: 'motivation' },
  { id: 11, text: 'Don\'t stop when you\'re tired. Stop when you\'re done.', author: 'Unknown', category: 'motivation' },
  { id: 12, text: 'Wake up with determination. Go to bed with satisfaction.', author: 'Unknown', category: 'motivation' },
  { id: 13, text: 'Do something today that your future self will thank you for.', author: 'Unknown', category: 'motivation' },
  { id: 14, text: 'Little things make big days.', author: 'Unknown', category: 'motivation' },
  { id: 15, text: 'It\'s going to be hard, but hard does not mean impossible.', author: 'Unknown', category: 'motivation' },
  { id: 16, text: 'Don\'t wait. The time will never be just right.', author: 'Napoleon Hill', category: 'motivation' },
  { id: 17, text: 'Start where you are. Use what you have. Do what you can.', author: 'Arthur Ashe', category: 'motivation' },
  { id: 18, text: 'The only limit to our realization of tomorrow will be our doubts of today.', author: 'Franklin D. Roosevelt', category: 'motivation' },
  { id: 19, text: 'Believe you can and you\'re halfway there.', author: 'Theodore Roosevelt', category: 'motivation' },
  { id: 20, text: 'Act as if what you do makes a difference. It does.', author: 'William James', category: 'motivation' },
  { id: 21, text: 'What you get by achieving your goals is not as important as what you become by achieving your goals.', author: 'Zig Ziglar', category: 'motivation' },
  { id: 22, text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', author: 'Winston S. Churchill', category: 'motivation' },
  { id: 23, text: 'The best revenge is massive success.', author: 'Frank Sinatra', category: 'motivation' },
  { id: 24, text: 'People often say that motivation doesn\'t last. Well, neither does bathing. That\'s why we recommend it daily.', author: 'Zig Ziglar', category: 'motivation' },
  { id: 25, text: 'I\'ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.', author: 'Maya Angelou', category: 'motivation' },
  { id: 26, text: 'Whether you think you can or you think you can\'t, you\'re right.', author: 'Henry Ford', category: 'motivation' },
  { id: 27, text: 'I have learned over the years that when one\'s mind is made up, this diminishes fear.', author: 'Rosa Parks', category: 'motivation' },
  { id: 28, text: 'Life is 10% what happens to me and 90% of how I react to it.', author: 'Charles Swindoll', category: 'motivation' },
  { id: 29, text: 'The most difficult thing is the decision to act, the rest is merely tenacity.', author: 'Amelia Earhart', category: 'motivation' },
  { id: 30, text: 'I didn\'t fail the test. I just found 100 ways to do it wrong.', author: 'Benjamin Franklin', category: 'motivation' },
  { id: 31, text: 'In order to succeed, your desire for success should be greater than your fear of failure.', author: 'Bill Cosby', category: 'motivation' },
  { id: 32, text: 'A person who never made a mistake never tried anything new.', author: 'Albert Einstein', category: 'motivation' },
  { id: 33, text: 'The person who says it cannot be done should not interrupt the person who is doing it.', author: 'Chinese Proverb', category: 'motivation' },
  { id: 34, text: 'There are no traffic jams along the extra mile.', author: 'Roger Staubach', category: 'motivation' },
  { id: 35, text: 'It is never too late to be what you might have been.', author: 'George Eliot', category: 'motivation' },
  { id: 36, text: 'You become what you believe.', author: 'Oprah Winfrey', category: 'motivation' },
  { id: 37, text: 'Build your own dreams, or someone else will hire you to build theirs.', author: 'Farrah Gray', category: 'motivation' },
  { id: 38, text: 'The battles that count aren\'t the ones for gold medals. The struggles within yourself—the invisible battles inside all of us—that\'s where it\'s at.', author: 'Jesse Owens', category: 'motivation' },
  { id: 39, text: 'Dream big and dare to fail.', author: 'Norman Vaughan', category: 'motivation' },
  { id: 40, text: 'Our lives begin to end the day we become silent about things that matter.', author: 'Martin Luther King Jr.', category: 'motivation' },
  { id: 41, text: 'Do what you can, where you are, with what you have.', author: 'Theodore Roosevelt', category: 'motivation' },
  { id: 42, text: 'If you do what you\'ve always done, you\'ll get what you\'ve always gotten.', author: 'Tony Robbins', category: 'motivation' },
  { id: 43, text: 'Dreaming, after all, is a form of planning.', author: 'Gloria Steinem', category: 'motivation' },
  { id: 44, text: 'You may be disappointed if you fail, but you are doomed if you don\'t try.', author: 'Beverly Sills', category: 'motivation' },
  { id: 45, text: 'Remember no one can make you feel inferior without your consent.', author: 'Eleanor Roosevelt', category: 'motivation' },
  { id: 46, text: 'Life is what we make it, always has been, always will be.', author: 'Grandma Moses', category: 'motivation' },
  { id: 47, text: 'The question isn\'t who is going to let me; it\'s who is going to stop me.', author: 'Ayn Rand', category: 'motivation' },
  { id: 48, text: 'When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.', author: 'Henry Ford', category: 'motivation' },
  { id: 49, text: 'I must not fear. Fear is the mind-killer.', author: 'Frank Herbert', category: 'motivation' },
  { id: 50, text: 'Attitude is a choice. Happiness is a choice. Optimism is a choice.', author: 'Roy T. Bennett', category: 'motivation' },
  { id: 51, text: 'Don\'t be pushed around by the fears in your mind. Be led by the dreams in your heart.', author: 'Roy T. Bennett', category: 'motivation' },
  { id: 52, text: 'Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.', author: 'Roy T. Bennett', category: 'motivation' },
  { id: 53, text: 'Live the life of your dreams according to your vision and purpose instead of the expectations and opinions of others.', author: 'Roy T. Bennett', category: 'motivation' },
  { id: 54, text: 'It\'s only after you\'ve stepped outside your comfort zone that you begin to change, grow, and transform.', author: 'Roy T. Bennett', category: 'motivation' },
  { id: 55, text: 'Let the improvement of yourself keep you so busy that you have no time to criticize others.', author: 'Roy T. Bennett', category: 'motivation' },
  { id: 56, text: 'Dare to be the best you can. At all times, dare to be!', author: 'Steve Maraboli', category: 'motivation' },
  { id: 57, text: 'Never lose hope. Storms make people stronger and never last forever.', author: 'Roy T. Bennett', category: 'motivation' },
  { id: 58, text: 'Do not fear failure but rather fear not trying.', author: 'Roy T. Bennett', category: 'motivation' },
  { id: 59, text: 'Do not let the memories of your past limit the potential of your future.', author: 'Roy T. Bennett', category: 'motivation' },
  { id: 60, text: 'Everything can be taken from a man but one thing: the last of the human freedoms—to choose one\'s attitude in any given set of circumstances.', author: 'Viktor E. Frankl', category: 'motivation' },
  { id: 61, text: 'You miss 100% of the shots you don\'t take.', author: 'Wayne Gretzky', category: 'motivation' },
  { id: 62, text: 'Every strike brings me closer to the next home run.', author: 'Babe Ruth', category: 'motivation' },
  { id: 63, text: 'Definiteness of purpose is the starting point of all achievement.', author: 'W. Clement Stone', category: 'motivation' },
  { id: 64, text: 'Life isn\'t about getting and having, it\'s about giving and being.', author: 'Kevin Kruse', category: 'motivation' },
  { id: 65, text: 'We become what we think about.', author: 'Earl Nightingale', category: 'motivation' },
  { id: 66, text: 'Your time is limited, so don\'t waste it living someone else\'s life.', author: 'Steve Jobs', category: 'motivation' },
  { id: 67, text: 'The best time to plant a tree was 20 years ago. The second best time is now.', author: 'Chinese Proverb', category: 'motivation' },
  { id: 68, text: 'Eighty percent of success is showing up.', author: 'Woody Allen', category: 'motivation' },
  { id: 69, text: 'I am not a product of my circumstances. I am a product of my decisions.', author: 'Stephen Covey', category: 'motivation' },
  { id: 70, text: 'Go confidently in the direction of your dreams. Live the life you have imagined.', author: 'Henry David Thoreau', category: 'motivation' },
  { id: 71, text: 'When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left.', author: 'Erma Bombeck', category: 'motivation' },
  { id: 72, text: 'Certain things catch your eye, but pursue only those that capture the heart.', author: 'Ancient Indian Proverb', category: 'motivation' },
  { id: 73, text: 'Everything you\'ve ever wanted is on the other side of fear.', author: 'George Addair', category: 'motivation' },
  { id: 74, text: 'We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.', author: 'Plato', category: 'motivation' },
  { id: 75, text: 'Fall seven times and stand up eight.', author: 'Japanese Proverb', category: 'motivation' },
  { id: 76, text: 'How wonderful it is that nobody need wait a single moment before starting to improve the world.', author: 'Anne Frank', category: 'motivation' },
  { id: 77, text: 'Too many of us are not living our dreams because we are living our fears.', author: 'Les Brown', category: 'motivation' },
  { id: 78, text: 'Challenges are what make life interesting and overcoming them is what makes life meaningful.', author: 'Joshua J. Marine', category: 'motivation' },
  { id: 79, text: 'I have been impressed with the urgency of doing. Knowing is not enough; we must apply.', author: 'Leonardo da Vinci', category: 'motivation' },
  { id: 80, text: 'Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.', author: 'Jamie Paolinetti', category: 'motivation' },
  { id: 81, text: 'Discipline is the bridge between goals and accomplishment.', author: 'Jim Rohn', category: 'discipline' },
  { id: 82, text: 'We must all suffer one of two things: the pain of discipline or the pain of regret.', author: 'Jim Rohn', category: 'discipline' },
  { id: 83, text: 'The successful warrior is the average man, with laser-like focus.', author: 'Bruce Lee', category: 'discipline' },
  { id: 84, text: 'Self-discipline begins with the mastery of your thoughts.', author: 'Earl Nightingale', category: 'discipline' },
  { id: 85, text: 'Discipline is choosing between what you want now and what you want most.', author: 'Abraham Lincoln', category: 'discipline' },
  { id: 86, text: 'No discipline seems pleasant at the time, but painful. Later on, however, it produces a harvest of righteousness and peace.', author: 'Hebrews 12:11', category: 'discipline' },
  { id: 87, text: 'Small disciplines repeated with consistency every day lead to great achievements gained slowly over time.', author: 'John Maxwell', category: 'discipline' },
  { id: 88, text: 'Discipline is just choosing between what you want now and what you want most.', author: 'Augusten Burroughs', category: 'discipline' },
  { id: 89, text: 'The first and best victory is to conquer self.', author: 'Plato', category: 'discipline' },
  { id: 90, text: 'With self-discipline, most anything is possible.', author: 'Theodore Roosevelt', category: 'discipline' },
  { id: 91, text: 'Discipline is the soul of an army. It makes small numbers formidable; procures success to the weak, and esteem to all.', author: 'George Washington', category: 'discipline' },
  { id: 92, text: 'He who cannot obey himself will be commanded. That is the nature of living creatures.', author: 'Friedrich Nietzsche', category: 'discipline' },
  { id: 93, text: 'Discipline is the foundation upon which all success is built. Lack of discipline inevitably leads to failure.', author: 'Jim Rohn', category: 'discipline' },
  { id: 94, text: 'The successful person has the habit of doing the things failures don\'t like to do. They don\'t like doing them either, necessarily. But their disliking is subordinated to the strength of their purpose.', author: 'E.M. Gray', category: 'discipline' },
  { id: 95, text: 'Without discipline, there\'s no life at all.', author: 'Katharine Hepburn', category: 'discipline' },
  { id: 96, text: 'I think self-awareness is probably the most important thing towards being a champion.', author: 'Billie Jean King', category: 'discipline' },
  { id: 97, text: 'The greatest glory in living lies not in never falling, but in rising every time we fall.', author: 'Ralph Waldo Emerson', category: 'discipline' },
  { id: 98, text: 'Discipline is the key to success. I can promise you that while other people may be talking, you\'ll be accomplishing.', author: 'Billie Jean King', category: 'discipline' },
  { id: 99, text: 'One of the healthiest habits a person can have is the discipline of early rising.', author: 'Thomas Fuller', category: 'discipline' },
  { id: 100, text: 'Self-control is strength. Right thought is mastery. Calmness is power.', author: 'James Allen', category: 'discipline' },
  { id: 101, text: 'It is not enough to have a good mind; the main thing is to use it well.', author: 'René Descartes', category: 'discipline' },
  { id: 102, text: 'The secret of change is to focus all of your energy not on fighting the old, but on building the new.', author: 'Socrates', category: 'discipline' },
  { id: 103, text: 'Self-discipline is when your conscience tells you to do something and you don\'t talk back.', author: 'W.K. Hope', category: 'discipline' },
  { id: 104, text: 'Motivation is what gets you started. Habit is what keeps you going.', author: 'Jim Rohn', category: 'discipline' },
  { id: 105, text: 'Discipline helps you finish a job, and finishing is what separates excellent work from average work.', author: 'Dan Gable', category: 'discipline' },
  { id: 106, text: 'Concentrate all your thoughts upon the work at hand. The sun\'s rays do not burn until brought to a focus.', author: 'Alexander Graham Bell', category: 'discipline' },
  { id: 107, text: 'Discipline is remembering what you want.', author: 'David Campbell', category: 'discipline' },
  { id: 108, text: 'There may be people who have more talent than you, but there\'s no excuse for anyone to work harder than you do.', author: 'Derek Jeter', category: 'discipline' },
  { id: 109, text: 'The ability to discipline yourself to delay gratification in the short term in order to enjoy greater rewards in the long term is the indispensable prerequisite for success.', author: 'Brian Tracy', category: 'discipline' },
  { id: 110, text: 'Self-discipline is a form of freedom. Freedom from laziness and lethargy, freedom from expectations and demands of others, freedom from weakness and fear—and doubt.', author: 'Gail Sheehy', category: 'discipline' },
  { id: 111, text: 'Without self-discipline, success is impossible, period.', author: 'Lee Haney', category: 'discipline' },
  { id: 112, text: 'Discipline is remembering what you want most.', author: 'David Campbell', category: 'discipline' },
  { id: 113, text: 'The will to win, the desire to succeed, the urge to reach your full potential — these are the keys that will unlock the door to personal excellence.', author: 'Confucius', category: 'discipline' },
  { id: 114, text: 'The pain of discipline is nothing like the pain of disappointment.', author: 'Justin Langer', category: 'discipline' },
  { id: 115, text: 'Discipline is the refining fire by which talent becomes ability.', author: 'Roy L. Smith', category: 'discipline' },
  { id: 116, text: 'You will never find time for anything. If you want time you must make it.', author: 'Charles Buxton', category: 'discipline' },
  { id: 117, text: 'Discipline equals freedom.', author: 'Jocko Willink', category: 'discipline' },
  { id: 118, text: 'It is well that there should be men without talent, for that is how discipline is born.', author: 'Anton Chekhov', category: 'discipline' },
  { id: 119, text: 'The greatest weapon against stress is our ability to choose one thought over another.', author: 'William James', category: 'discipline' },
  { id: 120, text: 'Hard work spotlights the character of people: some turn up their sleeves, some turn up their noses, and some don\'t turn up at all.', author: 'Sam Ewing', category: 'discipline' },
  { id: 121, text: 'The foundation of every great discipline is a strong will.', author: 'Napoleon Hill', category: 'discipline' },
  { id: 122, text: 'Discipline is the most powerful thought that can take your mind and turn it into the most powerful tool.', author: 'Robin Sharma', category: 'discipline' },
  { id: 123, text: 'The successful warrior is the average man with laser-like focus.', author: 'Bruce Lee', category: 'discipline' },
  { id: 124, text: 'I have three grand secrets: I listen, I listen, I listen.', author: 'Bruce Lee', category: 'discipline' },
  { id: 125, text: 'Strength does not come from the body. It comes from the will.', author: 'Epictetus', category: 'discipline' },
  { id: 126, text: 'To do what needs to be done when it needs to be done, whether you feel like it or not, is the essence of discipline.', author: 'Brian Tracy', category: 'discipline' },
  { id: 127, text: 'Self-discipline is the act of making yourself do what you should do, when you should do it, whether you feel like it or not.', author: 'Elbert Hubbard', category: 'discipline' },
  { id: 128, text: 'The price of discipline is always less than the pain of regret.', author: 'Nido Qubein', category: 'discipline' },
  { id: 129, text: 'It takes discipline to do what needs to be done when it needs to be done whether you feel like it or not.', author: 'Brian Tracy', category: 'discipline' },
  { id: 130, text: 'Discipline is the mother of all virtues.', author: 'John Wooden', category: 'discipline' },
  { id: 131, text: 'The more discipline there is, the more freedom there is.', author: 'Jocko Willink', category: 'discipline' },
  { id: 132, text: 'Discipline is the bridge between thought and accomplishment.', author: 'Jim Rohn', category: 'discipline' },
  { id: 133, text: 'The man who has no imagination has no wings.', author: 'Muhammad Ali', category: 'discipline' },
  { id: 134, text: 'Discipline is the fuel of achievement.', author: 'Earl Nightingale', category: 'discipline' },
  { id: 135, text: 'Self-discipline is the magic power that makes you virtually unstoppable.', author: 'Dan Kennedy', category: 'discipline' },
  { id: 136, text: 'Discipline is the soul of an army. It makes small numbers formidable.', author: 'George Washington', category: 'discipline' },
  { id: 137, text: 'The difference between the impossible and the possible lies in a person\'s determination.', author: 'Tommy Lasorda', category: 'discipline' },
  { id: 138, text: 'Self-discipline is essential to any achievement of lasting value.', author: 'Brian Tracy', category: 'discipline' },
  { id: 139, text: 'Without discipline, knowledge is useless.', author: 'Thomas Jefferson', category: 'discipline' },
  { id: 140, text: 'Discipline is remembering what you want and doing what it takes to get it.', author: 'David Campbell', category: 'discipline' },
  { id: 141, text: 'The successful person has the habit of doing the things failures don\'t like to do.', author: 'E.M. Gray', category: 'discipline' },
  { id: 142, text: 'The only way to get the best of an argument is to avoid it.', author: 'Dale Carnegie', category: 'discipline' },
  { id: 143, text: 'Discipline is the foundation upon which all success is built.', author: 'Jim Rohn', category: 'discipline' },
  { id: 144, text: 'I think the thing that makes a champion is the ability to stay focused.', author: 'Tiger Woods', category: 'discipline' },
  { id: 145, text: 'Discipline is the key to unlocking your potential.', author: 'Brian Tracy', category: 'discipline' },
  { id: 146, text: 'The most powerful weapon on earth is the human soul on fire.', author: 'Ferdinand Foch', category: 'discipline' },
  { id: 147, text: 'Discipline is the highest form of self-love.', author: 'Mandy Hale', category: 'discipline' },
  { id: 148, text: 'Small disciplines repeated with consistency every day lead to great achievements.', author: 'John Maxwell', category: 'discipline' },
  { id: 149, text: 'I can\'t give you a sure-fire formula for success, but I can give you a formula for failure: try to please everybody all the time.', author: 'Herbert Bayard Swope', category: 'success' },
  { id: 150, text: 'Try not to become a man of success. Rather become a man of value.', author: 'Albert Einstein', category: 'success' },
  { id: 151, text: 'Success is not how high you have climbed, but how you make a positive difference to the world.', author: 'Roy T. Bennett', category: 'success' },
  { id: 152, text: 'Don\'t spend time beating on a wall, hoping to transform it into a door.', author: 'Coco Chanel', category: 'success' },
  { id: 153, text: 'Success is getting what you want, happiness is wanting what you get.', author: 'W.P. Kinsella', category: 'success' },
  { id: 154, text: 'I\'m a success today because I had a friend who believed in me and I didn\'t have the heart to let him down.', author: 'Abraham Lincoln', category: 'success' },
  { id: 155, text: 'Our greatest glory is not in never falling, but in rising every time we fall.', author: 'Oliver Goldsmith', category: 'success' },
  { id: 156, text: 'It is hard to fail, but it is worse never to have tried to succeed.', author: 'Theodore Roosevelt', category: 'success' },
  { id: 157, text: 'Life is about making an impact, not making an income.', author: 'Kevin Kruse', category: 'success' },
  { id: 158, text: 'Whatever the mind of man can conceive and believe, it can achieve.', author: 'Napoleon Hill', category: 'success' },
  { id: 159, text: 'Strive not to be a success, but rather to be of value.', author: 'Albert Einstein', category: 'success' },
  { id: 160, text: 'I attribute my success to this: I never gave or took any excuse.', author: 'Florence Nightingale', category: 'success' },
  { id: 161, text: 'I\'ve missed more than 9000 shots in my career. I\'ve lost almost 300 games. I\'ve failed over and over and over again in my life. And that is why I succeed.', author: 'Michael Jordan', category: 'success' },
  { id: 162, text: 'The two most important days in your life are the day you are born and the day you find out why.', author: 'Mark Twain', category: 'success' },
  { id: 163, text: 'Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.', author: 'Johann Wolfgang von Goethe', category: 'success' },
  { id: 164, text: 'Either you run the day, or the day runs you.', author: 'Jim Rohn', category: 'success' },
  { id: 165, text: 'If you hear a voice within you say \'you cannot paint,\' then by all means paint and that voice will be silenced.', author: 'Vincent Van Gogh', category: 'success' },
  { id: 166, text: 'There is only one way to avoid criticism: do nothing, say nothing, and be nothing.', author: 'Aristotle', category: 'success' },
  { id: 167, text: 'The only person you are destined to become is the person you decide to be.', author: 'Ralph Waldo Emerson', category: 'success' },
  { id: 168, text: 'We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.', author: 'Marie Curie', category: 'success' },
  { id: 169, text: 'Success is the sum of small efforts, repeated day in and day out.', author: 'Robert Collier', category: 'success' },
  { id: 170, text: 'Courage is resistance to fear, mastery of fear—not absence of fear.', author: 'Mark Twain', category: 'success' },
  { id: 171, text: 'The way to get started is to quit talking and begin doing.', author: 'Walt Disney', category: 'success' },
  { id: 172, text: 'Success is walking from failure to failure with no loss of enthusiasm.', author: 'Winston Churchill', category: 'success' },
  { id: 173, text: 'Most great people have attained their greatest success just one step beyond their greatest failure.', author: 'Napoleon Hill', category: 'success' },
  { id: 174, text: 'Success is not the key to happiness. Happiness is the key to success.', author: 'Albert Schweitzer', category: 'success' },
  { id: 175, text: 'The real test is not whether you avoid this failure, because you won\'t. It\'s whether you let it harden or shame you into inaction.', author: 'Barack Obama', category: 'success' },
  { id: 176, text: 'The only place where success comes before work is in the dictionary.', author: 'Vidal Sassoon', category: 'success' },
  { id: 177, text: 'I find that the harder I work, the more luck I seem to have.', author: 'Thomas Jefferson', category: 'success' },
  { id: 178, text: 'Success usually comes to those who are too busy to be looking for it.', author: 'Henry David Thoreau', category: 'success' },
  { id: 179, text: 'Don\'t be afraid to give up the good to go for the great.', author: 'John D. Rockefeller', category: 'success' },
  { id: 180, text: 'I never dreamed about success, I worked for it.', author: 'Estée Lauder', category: 'success' },
  { id: 181, text: 'Success is liking yourself, liking what you do, and liking how you do it.', author: 'Maya Angelou', category: 'success' },
  { id: 182, text: 'The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.', author: 'Vince Lombardi', category: 'success' },
  { id: 183, text: 'Try not to become a man of success, but rather try to become a man of value.', author: 'Albert Einstein', category: 'success' },
  { id: 184, text: 'The road to success and the road to failure are almost exactly the same.', author: 'Colin R. Davis', category: 'success' },
  { id: 185, text: 'Opportunities don\'t happen. You create them.', author: 'Chris Grosser', category: 'success' },
  { id: 186, text: 'Don\'t let yesterday take up too much of today.', author: 'Will Rogers', category: 'success' },
  { id: 187, text: 'It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.', author: 'Charles Darwin', category: 'success' },
  { id: 188, text: 'Great things are done by a series of small things brought together.', author: 'Vincent Van Gogh', category: 'success' },
  { id: 189, text: 'The secret of success is to do the common thing uncommonly well.', author: 'John D. Rockefeller Jr.', category: 'success' },
  { id: 190, text: 'Success is not in what you have, but who you are.', author: 'Bo Bennett', category: 'success' },
  { id: 191, text: 'The greatest achievement was at first and for a time a dream. The oak sleeps in the acorn.', author: 'James Allen', category: 'success' },
  { id: 192, text: 'A successful man is one who can lay a firm foundation with the bricks others have thrown at him.', author: 'David Brinkley', category: 'success' },
  { id: 193, text: 'Don\'t be distracted by criticism. Remember: the only taste of success some people have is when they take a bite out of you.', author: 'Zig Ziglar', category: 'success' },
  { id: 194, text: 'Success is a lousy teacher. It seduces smart people into thinking they can\'t lose.', author: 'Bill Gates', category: 'success' },
  { id: 195, text: 'Perfection is not attainable, but if we chase perfection we can catch excellence.', author: 'Vince Lombardi', category: 'success' },
  { id: 196, text: 'Success is getting what you want. Happiness is wanting what you get.', author: 'W.P. Kinsella', category: 'success' },
  { id: 197, text: 'Sometimes life knocks you on your ass... get up, dust yourself off, and don\'t let her kick you again.', author: 'Steve Maraboli', category: 'success' },
  { id: 198, text: 'No great thing is created suddenly.', author: 'Epictetus', category: 'success' },
  { id: 199, text: 'The only real mistake is the one from which we learn nothing.', author: 'Henry Ford', category: 'success' },
  { id: 200, text: 'When you reach the end of your rope, tie a knot and hang on.', author: 'Franklin D. Roosevelt', category: 'success' },
  { id: 201, text: 'Always bear in mind that your own resolution to succeed is more important than any one thing.', author: 'Abraham Lincoln', category: 'success' },
  { id: 202, text: 'The harder the battle, the sweeter the victory.', author: 'Les Brown', category: 'success' },
  { id: 203, text: 'Formal education will make you a living; self-education will make you a fortune.', author: 'Jim Rohn', category: 'success' },
  { id: 204, text: 'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.', author: 'Albert Schweitzer', category: 'success' },
  { id: 205, text: 'The secret of success is constancy to purpose.', author: 'Benjamin Disraeli', category: 'success' },
  { id: 206, text: 'Success is not the absence of failure; it\'s the persistence through failure.', author: 'Aisha Tyler', category: 'success' },
  { id: 207, text: 'Success is going from failure to failure without losing your enthusiasm.', author: 'Winston Churchill', category: 'success' },
  { id: 208, text: 'If you really want to do something, you\'ll find a way. If you don\'t, you\'ll find an excuse.', author: 'Jim Rohn', category: 'success' },
  { id: 209, text: 'The distance between insanity and genius is measured only by success.', author: 'Bruce Feirstein', category: 'success' },
  { id: 210, text: 'The mind is everything. What you think you become.', author: 'Buddha', category: 'mindset' },
  { id: 211, text: 'If you want to change the world, start with yourself.', author: 'Mahatma Gandhi', category: 'mindset' },
  { id: 212, text: 'You don\'t have to be great to start, but you have to start to be great.', author: 'Zig Ziglar', category: 'mindset' },
  { id: 213, text: 'The biggest adventure you can take is to live the life of your dreams.', author: 'Oprah Winfrey', category: 'mindset' },
  { id: 214, text: 'Your limitation—it\'s only your imagination.', author: 'Unknown', category: 'mindset' },
  { id: 215, text: 'Great things never come from comfort zones.', author: 'Unknown', category: 'mindset' },
  { id: 216, text: 'Push yourself, because no one else is going to do it for you.', author: 'Unknown', category: 'mindset' },
  { id: 217, text: 'Dream it. Wish it. Do it.', author: 'Unknown', category: 'mindset' },
  { id: 218, text: 'Success doesn\'t just find you. You have to go out and get it.', author: 'Unknown', category: 'mindset' },
  { id: 219, text: 'What we think, we become.', author: 'Buddha', category: 'mindset' },
  { id: 220, text: 'Absorb what is useful. Discard what is not. Add what is uniquely your own.', author: 'Bruce Lee', category: 'mindset' },
  { id: 221, text: 'The only journey is the one within.', author: 'Rainer Maria Rilke', category: 'mindset' },
  { id: 222, text: 'Change your thoughts and you change your world.', author: 'Norman Vincent Peale', category: 'mindset' },
  { id: 223, text: 'The greatest discovery of all time is that a person can change their future by merely changing their attitude.', author: 'Oprah Winfrey', category: 'mindset' },
  { id: 224, text: 'Our mind is a garden, our thoughts are the seeds. We can grow flowers or we can grow weeds.', author: 'Unknown', category: 'mindset' },
  { id: 225, text: 'You are the master of your destiny. You can influence, direct and control your own environment.', author: 'Napoleon Hill', category: 'mindset' },
  { id: 226, text: 'The mind is just like a muscle—the more you exercise it, the stronger it gets.', author: 'Idowu Koyenikan', category: 'mindset' },
  { id: 227, text: 'If you believe it will work out, you\'ll see opportunities. If you believe it won\'t, you will see obstacles.', author: 'Wayne Dyer', category: 'mindset' },
  { id: 228, text: 'A positive attitude causes a chain reaction of positive thoughts, events, and outcomes.', author: 'Wade Boggs', category: 'mindset' },
  { id: 229, text: 'The most powerful relationship you will ever have is the relationship with yourself.', author: 'Steve Maraboli', category: 'mindset' },
  { id: 230, text: 'The biggest room in the world is the room for improvement.', author: 'Helmut Schmidt', category: 'mindset' },
  { id: 231, text: 'The only way to make sense out of change is to plunge into it, move with it, and join the dance.', author: 'Alan Watts', category: 'mindset' },
  { id: 232, text: 'Your attitude, not your aptitude, will determine your altitude.', author: 'Zig Ziglar', category: 'mindset' },
  { id: 233, text: 'The mind is not a vessel to be filled, but a fire to be kindled.', author: 'Plutarch', category: 'mindset' },
  { id: 234, text: 'It is the mark of an educated mind to be able to entertain a thought without accepting it.', author: 'Aristotle', category: 'mindset' },
  { id: 235, text: 'The best way to predict the future is to create it.', author: 'Peter Drucker', category: 'mindset' },
  { id: 236, text: 'Once you change your philosophy, you change your thought process.', author: 'Larry Winget', category: 'mindset' },
  { id: 237, text: 'There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self.', author: 'Ernest Hemingway', category: 'self_development' },
  { id: 238, text: 'One ought, every day at least, to hear a little song, read a good poem, see a fine picture.', author: 'Johann Wolfgang von Goethe', category: 'self_development' },
  { id: 239, text: 'Those who cannot change their minds cannot change anything.', author: 'George Bernard Shaw', category: 'self_development' },
  { id: 240, text: 'A proud man is always looking down on things and people; and, of course, as long as you are looking down, you cannot see something that is above you.', author: 'C.S. Lewis', category: 'self_development' },
  { id: 241, text: 'Make the most of yourself...for that is all there is of you.', author: 'Ralph Waldo Emerson', category: 'self_development' },
  { id: 242, text: 'Always dream and shoot higher than you know you can do.', author: 'William Faulkner', category: 'self_development' },
  { id: 243, text: 'Once we accept our limits, we go beyond them.', author: 'Albert Einstein', category: 'self_development' },
  { id: 244, text: 'No matter who you are, no matter what you did, no matter where you\'ve come from, you can always change, become a better version of yourself.', author: 'Madonna', category: 'self_development' },
  { id: 245, text: 'The curious paradox is that when I accept myself just as I am, then I can change.', author: 'Carl R. Rogers', category: 'self_development' },
  { id: 246, text: 'There is only one corner of the universe you can be certain of improving, and that\'s your own self.', author: 'Aldous Huxley', category: 'self_development' },
  { id: 247, text: 'I like to listen. I have learned a great deal from listening carefully. Most people never listen.', author: 'Ernest Hemingway', category: 'self_development' },
  { id: 248, text: 'A strong man cannot help a weaker unless the weaker is willing to be helped.', author: 'James Allen', category: 'self_development' },
  { id: 249, text: 'You are what you repeatedly do. Excellence, then, is not an act but a habit.', author: 'Aristotle', category: 'self_development' },
  { id: 250, text: 'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.', author: 'Ralph Waldo Emerson', category: 'self_development' },
  { id: 251, text: 'Knowing others is intelligence; knowing yourself is true wisdom.', author: 'Lao Tzu', category: 'self_development' },
  { id: 252, text: 'He who conquers himself is the mightiest warrior.', author: 'Confucius', category: 'self_development' },
  { id: 253, text: 'Be the change that you wish to see in the world.', author: 'Mahatma Gandhi', category: 'self_development' },
  { id: 254, text: 'The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.', author: 'Marcel Proust', category: 'self_development' },
  { id: 255, text: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', author: 'Ralph Waldo Emerson', category: 'self_development' },
  { id: 256, text: 'The battles that count aren\'t the ones for gold medals. The struggles within yourself—that\'s where it\'s at.', author: 'Jesse Owens', category: 'self_development' },
  { id: 257, text: 'Hard work spotlights the character of people.', author: 'Sam Ewing', category: 'self_development' },
  { id: 258, text: 'Self-discipline is the act of making yourself do what you should do.', author: 'Elbert Hubbard', category: 'self_development' },
  { id: 259, text: 'Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.', author: 'Robert Frost', category: 'life_wisdom' },
  { id: 260, text: 'Life is what happens to you while you\'re busy making other plans.', author: 'John Lennon', category: 'life_wisdom' },
  { id: 261, text: 'Twenty years from now you will be more disappointed by the things that you didn\'t do than by the ones you did do.', author: 'Mark Twain', category: 'life_wisdom' },
  { id: 262, text: 'An unexamined life is not worth living.', author: 'Socrates', category: 'life_wisdom' },
  { id: 263, text: 'When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.', author: 'Helen Keller', category: 'life_wisdom' },
  { id: 264, text: 'Everything has beauty, but not everyone can see.', author: 'Confucius', category: 'life_wisdom' },
  { id: 265, text: 'Happiness is not something readymade. It comes from your own actions.', author: 'Dalai Lama', category: 'life_wisdom' },
  { id: 266, text: 'If you\'re offered a seat on a rocket ship, don\'t ask what seat! Just get on.', author: 'Sheryl Sandberg', category: 'life_wisdom' },
  { id: 267, text: 'What\'s money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.', author: 'Bob Dylan', category: 'life_wisdom' },
  { id: 268, text: 'If you look at what you have in life, you\'ll always have more.', author: 'Oprah Winfrey', category: 'life_wisdom' },
  { id: 269, text: 'Remember that not getting what you want is sometimes a wonderful stroke of luck.', author: 'Dalai Lama', category: 'life_wisdom' },
  { id: 270, text: 'You can\'t use up creativity. The more you use, the more you have.', author: 'Maya Angelou', category: 'life_wisdom' },
  { id: 271, text: 'It\'s your place in the world; it\'s your life. Go on and do all you can with it.', author: 'Mae Jemison', category: 'life_wisdom' },
  { id: 272, text: 'When I let go of what I am, I become what I might be.', author: 'Lao Tzu', category: 'life_wisdom' },
  { id: 273, text: 'Life is not measured by the number of breaths we take, but by the moments that take our breath away.', author: 'Maya Angelou', category: 'life_wisdom' },
  { id: 274, text: 'If you want to lift yourself up, lift up someone else.', author: 'Booker T. Washington', category: 'life_wisdom' },
  { id: 275, text: 'When I was 5 years old, my mother always told me that happiness was the key to life.', author: 'John Lennon', category: 'life_wisdom' },
  { id: 276, text: 'Teach thy tongue to say, \'I do not know,\' and thou shalt progress.', author: 'Maimonides', category: 'life_wisdom' },
  { id: 277, text: 'When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.', author: 'Erma Bombeck', category: 'life_wisdom' },
  { id: 278, text: 'First, have a definite, clear practical ideal; a goal, an objective.', author: 'Aristotle', category: 'life_wisdom' },
  { id: 279, text: 'If the wind will not serve, take to the oars.', author: 'Latin Proverb', category: 'life_wisdom' },
];
