/**
 * Motivational quotes bundled with the app (cleaned from the user-provided
 * dataset: duplicate quotes removed, the duplicate "Appendix" category
 * dropped). Used by the Quotes notification feature and the Quote widget.
 *
 * ids 280-582: short quotes (2 lines or less) sourced from "1001
 * Motivational Quotes for Success" by Thomas J. Vilord, filed under
 * 'success'. 3 quotes already present in the base set were skipped.
 */

export const QUOTE_CATEGORIES = [
  { id: 'motivation', label: { en: 'Motivation', ar: 'التحفيز' } },
  { id: 'discipline', label: { en: 'Discipline', ar: 'الانضباط' } },
  { id: 'success', label: { en: 'Success', ar: 'النجاح' } },
  { id: 'mindset', label: { en: 'Mindset', ar: 'العقلية' } },
  { id: 'self_development', label: { en: 'Self-Development', ar: 'تطوير الذات' } },
  { id: 'life_wisdom', label: { en: 'Life Wisdom', ar: 'حكمة الحياة' } },
];

export const QUOTES = [
  { id: 1, text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs', category: 'motivation' },
  { id: 2, text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius', category: 'motivation' },
  { id: 3, text: 'The future belongs to those who believe in the beauty of their dreams.', author: 'Eleanor Roosevelt', category: 'motivation' },
  { id: 4, text: 'The only impossible journey is the one you never begin.', author: 'Tony Robbins', category: 'motivation' },
  { id: 5, text: 'Don\'t watch the clock; do what it does. Keep going.', author: 'Sam Levenson', category: 'motivation' },
  { id: 6, text: 'It always seems impossible until it\'s done.', author: 'Nelson Mandela', category: 'motivation' },
  { id: 7, text: 'The secret of getting ahead is getting started.', author: 'Mark Twain', category: 'motivation' },
  { id: 8, text: 'You are never too old to set another goal or to dream a new dream.', author: 'C.S. Lewis', category: 'motivation' },
  { id: 9, text: 'The harder you work for something, the greater you\'ll feel when you achieve it.', author: 'Unknown', category: 'motivation' },
  { id: 10, text: 'Dream bigger. Do bigger.', author: 'Unknown', category: 'motivation' },
  { id: 11, text: 'Don\'t stop when you\'re tired. Stop when you\'re done.', author: 'Unknown', category: 'motivation' },
  { id: 12, text: 'Wake up with determination. Go to bed with satisfaction.', author: 'Unknown', category: 'motivation' },
  { id: 13, text: 'Do something today that your future self will thank you for.', author: 'Unknown', category: 'motivation' },
  { id: 14, text: 'Little things make big days.', author: 'Unknown', category: 'motivation' },
  { id: 15, text: 'It\'s going to be hard, but hard does not mean impossible.', author: 'Unknown', category: 'motivation' },
  { id: 16, text: 'Don\'t wait. The time will never be just right.', author: 'Napoleon Hill', category: 'motivation' },
  { id: 17, text: 'Start where you are. Use what you have. Do what you can.', author: 'Arthur Ashe', category: 'motivation' },
  { id: 18, text: 'The only limit to our realization of tomorrow will be our doubts of today.', author: 'Franklin D. Roosevelt', category: 'motivation' },
  { id: 19, text: 'Believe you can and you\'re halfway there.', author: 'Theodore Roosevelt', category: 'motivation' },
  { id: 20, text: 'Act as if what you do makes a difference. It does.', author: 'William James', category: 'motivation' },
  { id: 21, text: 'What you get by achieving your goals is not as important as what you become by achieving your goals.', author: 'Zig Ziglar', category: 'motivation' },
  { id: 22, text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', author: 'Winston S. Churchill', category: 'motivation' },
  { id: 23, text: 'The best revenge is massive success.', author: 'Frank Sinatra', category: 'motivation' },
  { id: 24, text: 'People often say that motivation doesn\'t last. Well, neither does bathing. That\'s why we recommend it daily.', author: 'Zig Ziglar', category: 'motivation' },
  { id: 25, text: 'I\'ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.', author: 'Maya Angelou', category: 'motivation' },
  { id: 26, text: 'Whether you think you can or you think you can\'t, you\'re right.', author: 'Henry Ford', category: 'motivation' },
  { id: 27, text: 'I have learned over the years that when one\'s mind is made up, this diminishes fear.', author: 'Rosa Parks', category: 'motivation' },
  { id: 28, text: 'Life is 10% what happens to me and 90% of how I react to it.', author: 'Charles Swindoll', category: 'motivation' },
  { id: 29, text: 'The most difficult thing is the decision to act, the rest is merely tenacity.', author: 'Amelia Earhart', category: 'motivation' },
  { id: 30, text: 'I didn\'t fail the test. I just found 100 ways to do it wrong.', author: 'Benjamin Franklin', category: 'motivation' },
  { id: 31, text: 'In order to succeed, your desire for success should be greater than your fear of failure.', author: 'Bill Cosby', category: 'motivation' },
  { id: 32, text: 'A person who never made a mistake never tried anything new.', author: 'Albert Einstein', category: 'motivation' },
  { id: 33, text: 'The person who says it cannot be done should not interrupt the person who is doing it.', author: 'Chinese Proverb', category: 'motivation' },
  { id: 34, text: 'There are no traffic jams along the extra mile.', author: 'Roger Staubach', category: 'motivation' },
  { id: 35, text: 'It is never too late to be what you might have been.', author: 'George Eliot', category: 'motivation' },
  { id: 36, text: 'You become what you believe.', author: 'Oprah Winfrey', category: 'motivation' },
  { id: 37, text: 'Build your own dreams, or someone else will hire you to build theirs.', author: 'Farrah Gray', category: 'motivation' },
  { id: 38, text: 'The battles that count aren\'t the ones for gold medals. The struggles within yourself—the invisible battles inside all of us—that\'s where it\'s at.', author: 'Jesse Owens', category: 'motivation' },
  { id: 39, text: 'Dream big and dare to fail.', author: 'Norman Vaughan', category: 'motivation' },
  { id: 40, text: 'Our lives begin to end the day we become silent about things that matter.', author: 'Martin Luther King Jr.', category: 'motivation' },
  { id: 41, text: 'Do what you can, where you are, with what you have.', author: 'Theodore Roosevelt', category: 'motivation' },
  { id: 42, text: 'If you do what you\'ve always done, you\'ll get what you\'ve always gotten.', author: 'Tony Robbins', category: 'motivation' },
  { id: 43, text: 'Dreaming, after all, is a form of planning.', author: 'Gloria Steinem', category: 'motivation' },
  { id: 44, text: 'You may be disappointed if you fail, but you are doomed if you don\'t try.', author: 'Beverly Sills', category: 'motivation' },
  { id: 45, text: 'Remember no one can make you feel inferior without your consent.', author: 'Eleanor Roosevelt', category: 'motivation' },
  { id: 46, text: 'Life is what we make it, always has been, always will be.', author: 'Grandma Moses', category: 'motivation' },
  { id: 47, text: 'The question isn\'t who is going to let me; it\'s who is going to stop me.', author: 'Ayn Rand', category: 'motivation' },
  { id: 48, text: 'When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.', author: 'Henry Ford', category: 'motivation' },
  { id: 49, text: 'I must not fear. Fear is the mind-killer.', author: 'Frank Herbert', category: 'motivation' },
  { id: 50, text: 'Attitude is a choice. Happiness is a choice. Optimism is a choice.', author: 'Roy T. Bennett', category: 'motivation' },
  { id: 51, text: 'Don\'t be pushed around by the fears in your mind. Be led by the dreams in your heart.', author: 'Roy T. Bennett', category: 'motivation' },
  { id: 52, text: 'Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.', author: 'Roy T. Bennett', category: 'motivation' },
  { id: 53, text: 'Live the life of your dreams according to your vision and purpose instead of the expectations and opinions of others.', author: 'Roy T. Bennett', category: 'motivation' },
  { id: 54, text: 'It\'s only after you\'ve stepped outside your comfort zone that you begin to change, grow, and transform.', author: 'Roy T. Bennett', category: 'motivation' },
  { id: 55, text: 'Let the improvement of yourself keep you so busy that you have no time to criticize others.', author: 'Roy T. Bennett', category: 'motivation' },
  { id: 56, text: 'Dare to be the best you can. At all times, dare to be!', author: 'Steve Maraboli', category: 'motivation' },
  { id: 57, text: 'Never lose hope. Storms make people stronger and never last forever.', author: 'Roy T. Bennett', category: 'motivation' },
  { id: 58, text: 'Do not fear failure but rather fear not trying.', author: 'Roy T. Bennett', category: 'motivation' },
  { id: 59, text: 'Do not let the memories of your past limit the potential of your future.', author: 'Roy T. Bennett', category: 'motivation' },
  { id: 60, text: 'Everything can be taken from a man but one thing: the last of the human freedoms—to choose one\'s attitude in any given set of circumstances.', author: 'Viktor E. Frankl', category: 'motivation' },
  { id: 61, text: 'You miss 100% of the shots you don\'t take.', author: 'Wayne Gretzky', category: 'motivation' },
  { id: 62, text: 'Every strike brings me closer to the next home run.', author: 'Babe Ruth', category: 'motivation' },
  { id: 63, text: 'Definiteness of purpose is the starting point of all achievement.', author: 'W. Clement Stone', category: 'motivation' },
  { id: 64, text: 'Life isn\'t about getting and having, it\'s about giving and being.', author: 'Kevin Kruse', category: 'motivation' },
  { id: 65, text: 'We become what we think about.', author: 'Earl Nightingale', category: 'motivation' },
  { id: 66, text: 'Your time is limited, so don\'t waste it living someone else\'s life.', author: 'Steve Jobs', category: 'motivation' },
  { id: 67, text: 'The best time to plant a tree was 20 years ago. The second best time is now.', author: 'Chinese Proverb', category: 'motivation' },
  { id: 68, text: 'Eighty percent of success is showing up.', author: 'Woody Allen', category: 'motivation' },
  { id: 69, text: 'I am not a product of my circumstances. I am a product of my decisions.', author: 'Stephen Covey', category: 'motivation' },
  { id: 70, text: 'Go confidently in the direction of your dreams. Live the life you have imagined.', author: 'Henry David Thoreau', category: 'motivation' },
  { id: 71, text: 'When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left.', author: 'Erma Bombeck', category: 'motivation' },
  { id: 72, text: 'Certain things catch your eye, but pursue only those that capture the heart.', author: 'Ancient Indian Proverb', category: 'motivation' },
  { id: 73, text: 'Everything you\'ve ever wanted is on the other side of fear.', author: 'George Addair', category: 'motivation' },
  { id: 74, text: 'We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.', author: 'Plato', category: 'motivation' },
  { id: 75, text: 'Fall seven times and stand up eight.', author: 'Japanese Proverb', category: 'motivation' },
  { id: 76, text: 'How wonderful it is that nobody need wait a single moment before starting to improve the world.', author: 'Anne Frank', category: 'motivation' },
  { id: 77, text: 'Too many of us are not living our dreams because we are living our fears.', author: 'Les Brown', category: 'motivation' },
  { id: 78, text: 'Challenges are what make life interesting and overcoming them is what makes life meaningful.', author: 'Joshua J. Marine', category: 'motivation' },
  { id: 79, text: 'I have been impressed with the urgency of doing. Knowing is not enough; we must apply.', author: 'Leonardo da Vinci', category: 'motivation' },
  { id: 80, text: 'Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.', author: 'Jamie Paolinetti', category: 'motivation' },
  { id: 81, text: 'Discipline is the bridge between goals and accomplishment.', author: 'Jim Rohn', category: 'discipline' },
  { id: 82, text: 'We must all suffer one of two things: the pain of discipline or the pain of regret.', author: 'Jim Rohn', category: 'discipline' },
  { id: 83, text: 'The successful warrior is the average man, with laser-like focus.', author: 'Bruce Lee', category: 'discipline' },
  { id: 84, text: 'Self-discipline begins with the mastery of your thoughts.', author: 'Earl Nightingale', category: 'discipline' },
  { id: 85, text: 'Discipline is choosing between what you want now and what you want most.', author: 'Abraham Lincoln', category: 'discipline' },
  { id: 86, text: 'No discipline seems pleasant at the time, but painful. Later on, however, it produces a harvest of righteousness and peace.', author: 'Hebrews 12:11', category: 'discipline' },
  { id: 87, text: 'Small disciplines repeated with consistency every day lead to great achievements gained slowly over time.', author: 'John Maxwell', category: 'discipline' },
  { id: 88, text: 'Discipline is just choosing between what you want now and what you want most.', author: 'Augusten Burroughs', category: 'discipline' },
  { id: 89, text: 'The first and best victory is to conquer self.', author: 'Plato', category: 'discipline' },
  { id: 90, text: 'With self-discipline, most anything is possible.', author: 'Theodore Roosevelt', category: 'discipline' },
  { id: 91, text: 'Discipline is the soul of an army. It makes small numbers formidable; procures success to the weak, and esteem to all.', author: 'George Washington', category: 'discipline' },
  { id: 92, text: 'He who cannot obey himself will be commanded. That is the nature of living creatures.', author: 'Friedrich Nietzsche', category: 'discipline' },
  { id: 93, text: 'Discipline is the foundation upon which all success is built. Lack of discipline inevitably leads to failure.', author: 'Jim Rohn', category: 'discipline' },
  { id: 94, text: 'The successful person has the habit of doing the things failures don\'t like to do. They don\'t like doing them either, necessarily. But their disliking is subordinated to the strength of their purpose.', author: 'E.M. Gray', category: 'discipline' },
  { id: 95, text: 'Without discipline, there\'s no life at all.', author: 'Katharine Hepburn', category: 'discipline' },
  { id: 96, text: 'I think self-awareness is probably the most important thing towards being a champion.', author: 'Billie Jean King', category: 'discipline' },
  { id: 97, text: 'The greatest glory in living lies not in never falling, but in rising every time we fall.', author: 'Ralph Waldo Emerson', category: 'discipline' },
  { id: 98, text: 'Discipline is the key to success. I can promise you that while other people may be talking, you\'ll be accomplishing.', author: 'Billie Jean King', category: 'discipline' },
  { id: 99, text: 'One of the healthiest habits a person can have is the discipline of early rising.', author: 'Thomas Fuller', category: 'discipline' },
  { id: 100, text: 'Self-control is strength. Right thought is mastery. Calmness is power.', author: 'James Allen', category: 'discipline' },
  { id: 101, text: 'It is not enough to have a good mind; the main thing is to use it well.', author: 'René Descartes', category: 'discipline' },
  { id: 102, text: 'The secret of change is to focus all of your energy not on fighting the old, but on building the new.', author: 'Socrates', category: 'discipline' },
  { id: 103, text: 'Self-discipline is when your conscience tells you to do something and you don\'t talk back.', author: 'W.K. Hope', category: 'discipline' },
  { id: 104, text: 'Motivation is what gets you started. Habit is what keeps you going.', author: 'Jim Rohn', category: 'discipline' },
  { id: 105, text: 'Discipline helps you finish a job, and finishing is what separates excellent work from average work.', author: 'Dan Gable', category: 'discipline' },
  { id: 106, text: 'Concentrate all your thoughts upon the work at hand. The sun\'s rays do not burn until brought to a focus.', author: 'Alexander Graham Bell', category: 'discipline' },
  { id: 107, text: 'Discipline is remembering what you want.', author: 'David Campbell', category: 'discipline' },
  { id: 108, text: 'There may be people who have more talent than you, but there\'s no excuse for anyone to work harder than you do.', author: 'Derek Jeter', category: 'discipline' },
  { id: 109, text: 'The ability to discipline yourself to delay gratification in the short term in order to enjoy greater rewards in the long term is the indispensable prerequisite for success.', author: 'Brian Tracy', category: 'discipline' },
  { id: 110, text: 'Self-discipline is a form of freedom. Freedom from laziness and lethargy, freedom from expectations and demands of others, freedom from weakness and fear—and doubt.', author: 'Gail Sheehy', category: 'discipline' },
  { id: 111, text: 'Without self-discipline, success is impossible, period.', author: 'Lee Haney', category: 'discipline' },
  { id: 112, text: 'Discipline is remembering what you want most.', author: 'David Campbell', category: 'discipline' },
  { id: 113, text: 'The will to win, the desire to succeed, the urge to reach your full potential — these are the keys that will unlock the door to personal excellence.', author: 'Confucius', category: 'discipline' },
  { id: 114, text: 'The pain of discipline is nothing like the pain of disappointment.', author: 'Justin Langer', category: 'discipline' },
  { id: 115, text: 'Discipline is the refining fire by which talent becomes ability.', author: 'Roy L. Smith', category: 'discipline' },
  { id: 116, text: 'You will never find time for anything. If you want time you must make it.', author: 'Charles Buxton', category: 'discipline' },
  { id: 117, text: 'Discipline equals freedom.', author: 'Jocko Willink', category: 'discipline' },
  { id: 118, text: 'It is well that there should be men without talent, for that is how discipline is born.', author: 'Anton Chekhov', category: 'discipline' },
  { id: 119, text: 'The greatest weapon against stress is our ability to choose one thought over another.', author: 'William James', category: 'discipline' },
  { id: 120, text: 'Hard work spotlights the character of people: some turn up their sleeves, some turn up their noses, and some don\'t turn up at all.', author: 'Sam Ewing', category: 'discipline' },
  { id: 121, text: 'The foundation of every great discipline is a strong will.', author: 'Napoleon Hill', category: 'discipline' },
  { id: 122, text: 'Discipline is the most powerful thought that can take your mind and turn it into the most powerful tool.', author: 'Robin Sharma', category: 'discipline' },
  { id: 123, text: 'The successful warrior is the average man with laser-like focus.', author: 'Bruce Lee', category: 'discipline' },
  { id: 124, text: 'I have three grand secrets: I listen, I listen, I listen.', author: 'Bruce Lee', category: 'discipline' },
  { id: 125, text: 'Strength does not come from the body. It comes from the will.', author: 'Epictetus', category: 'discipline' },
  { id: 126, text: 'To do what needs to be done when it needs to be done, whether you feel like it or not, is the essence of discipline.', author: 'Brian Tracy', category: 'discipline' },
  { id: 127, text: 'Self-discipline is the act of making yourself do what you should do, when you should do it, whether you feel like it or not.', author: 'Elbert Hubbard', category: 'discipline' },
  { id: 128, text: 'The price of discipline is always less than the pain of regret.', author: 'Nido Qubein', category: 'discipline' },
  { id: 129, text: 'It takes discipline to do what needs to be done when it needs to be done whether you feel like it or not.', author: 'Brian Tracy', category: 'discipline' },
  { id: 130, text: 'Discipline is the mother of all virtues.', author: 'John Wooden', category: 'discipline' },
  { id: 131, text: 'The more discipline there is, the more freedom there is.', author: 'Jocko Willink', category: 'discipline' },
  { id: 132, text: 'Discipline is the bridge between thought and accomplishment.', author: 'Jim Rohn', category: 'discipline' },
  { id: 133, text: 'The man who has no imagination has no wings.', author: 'Muhammad Ali', category: 'discipline' },
  { id: 134, text: 'Discipline is the fuel of achievement.', author: 'Earl Nightingale', category: 'discipline' },
  { id: 135, text: 'Self-discipline is the magic power that makes you virtually unstoppable.', author: 'Dan Kennedy', category: 'discipline' },
  { id: 136, text: 'Discipline is the soul of an army. It makes small numbers formidable.', author: 'George Washington', category: 'discipline' },
  { id: 137, text: 'The difference between the impossible and the possible lies in a person\'s determination.', author: 'Tommy Lasorda', category: 'discipline' },
  { id: 138, text: 'Self-discipline is essential to any achievement of lasting value.', author: 'Brian Tracy', category: 'discipline' },
  { id: 139, text: 'Without discipline, knowledge is useless.', author: 'Thomas Jefferson', category: 'discipline' },
  { id: 140, text: 'Discipline is remembering what you want and doing what it takes to get it.', author: 'David Campbell', category: 'discipline' },
  { id: 141, text: 'The successful person has the habit of doing the things failures don\'t like to do.', author: 'E.M. Gray', category: 'discipline' },
  { id: 142, text: 'The only way to get the best of an argument is to avoid it.', author: 'Dale Carnegie', category: 'discipline' },
  { id: 143, text: 'Discipline is the foundation upon which all success is built.', author: 'Jim Rohn', category: 'discipline' },
  { id: 144, text: 'I think the thing that makes a champion is the ability to stay focused.', author: 'Tiger Woods', category: 'discipline' },
  { id: 145, text: 'Discipline is the key to unlocking your potential.', author: 'Brian Tracy', category: 'discipline' },
  { id: 146, text: 'The most powerful weapon on earth is the human soul on fire.', author: 'Ferdinand Foch', category: 'discipline' },
  { id: 147, text: 'Discipline is the highest form of self-love.', author: 'Mandy Hale', category: 'discipline' },
  { id: 148, text: 'Small disciplines repeated with consistency every day lead to great achievements.', author: 'John Maxwell', category: 'discipline' },
  { id: 149, text: 'I can\'t give you a sure-fire formula for success, but I can give you a formula for failure: try to please everybody all the time.', author: 'Herbert Bayard Swope', category: 'success' },
  { id: 150, text: 'Try not to become a man of success. Rather become a man of value.', author: 'Albert Einstein', category: 'success' },
  { id: 151, text: 'Success is not how high you have climbed, but how you make a positive difference to the world.', author: 'Roy T. Bennett', category: 'success' },
  { id: 152, text: 'Don\'t spend time beating on a wall, hoping to transform it into a door.', author: 'Coco Chanel', category: 'success' },
  { id: 153, text: 'Success is getting what you want, happiness is wanting what you get.', author: 'W.P. Kinsella', category: 'success' },
  { id: 154, text: 'I\'m a success today because I had a friend who believed in me and I didn\'t have the heart to let him down.', author: 'Abraham Lincoln', category: 'success' },
  { id: 155, text: 'Our greatest glory is not in never falling, but in rising every time we fall.', author: 'Oliver Goldsmith', category: 'success' },
  { id: 156, text: 'It is hard to fail, but it is worse never to have tried to succeed.', author: 'Theodore Roosevelt', category: 'success' },
  { id: 157, text: 'Life is about making an impact, not making an income.', author: 'Kevin Kruse', category: 'success' },
  { id: 158, text: 'Whatever the mind of man can conceive and believe, it can achieve.', author: 'Napoleon Hill', category: 'success' },
  { id: 159, text: 'Strive not to be a success, but rather to be of value.', author: 'Albert Einstein', category: 'success' },
  { id: 160, text: 'I attribute my success to this: I never gave or took any excuse.', author: 'Florence Nightingale', category: 'success' },
  { id: 161, text: 'I\'ve missed more than 9000 shots in my career. I\'ve lost almost 300 games. I\'ve failed over and over and over again in my life. And that is why I succeed.', author: 'Michael Jordan', category: 'success' },
  { id: 162, text: 'The two most important days in your life are the day you are born and the day you find out why.', author: 'Mark Twain', category: 'success' },
  { id: 163, text: 'Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.', author: 'Johann Wolfgang von Goethe', category: 'success' },
  { id: 164, text: 'Either you run the day, or the day runs you.', author: 'Jim Rohn', category: 'success' },
  { id: 165, text: 'If you hear a voice within you say \'you cannot paint,\' then by all means paint and that voice will be silenced.', author: 'Vincent Van Gogh', category: 'success' },
  { id: 166, text: 'There is only one way to avoid criticism: do nothing, say nothing, and be nothing.', author: 'Aristotle', category: 'success' },
  { id: 167, text: 'The only person you are destined to become is the person you decide to be.', author: 'Ralph Waldo Emerson', category: 'success' },
  { id: 168, text: 'We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.', author: 'Marie Curie', category: 'success' },
  { id: 169, text: 'Success is the sum of small efforts, repeated day in and day out.', author: 'Robert Collier', category: 'success' },
  { id: 170, text: 'Courage is resistance to fear, mastery of fear—not absence of fear.', author: 'Mark Twain', category: 'success' },
  { id: 171, text: 'The way to get started is to quit talking and begin doing.', author: 'Walt Disney', category: 'success' },
  { id: 172, text: 'Success is walking from failure to failure with no loss of enthusiasm.', author: 'Winston Churchill', category: 'success' },
  { id: 173, text: 'Most great people have attained their greatest success just one step beyond their greatest failure.', author: 'Napoleon Hill', category: 'success' },
  { id: 174, text: 'Success is not the key to happiness. Happiness is the key to success.', author: 'Albert Schweitzer', category: 'success' },
  { id: 175, text: 'The real test is not whether you avoid this failure, because you won\'t. It\'s whether you let it harden or shame you into inaction.', author: 'Barack Obama', category: 'success' },
  { id: 176, text: 'The only place where success comes before work is in the dictionary.', author: 'Vidal Sassoon', category: 'success' },
  { id: 177, text: 'I find that the harder I work, the more luck I seem to have.', author: 'Thomas Jefferson', category: 'success' },
  { id: 178, text: 'Success usually comes to those who are too busy to be looking for it.', author: 'Henry David Thoreau', category: 'success' },
  { id: 179, text: 'Don\'t be afraid to give up the good to go for the great.', author: 'John D. Rockefeller', category: 'success' },
  { id: 180, text: 'I never dreamed about success, I worked for it.', author: 'Estée Lauder', category: 'success' },
  { id: 181, text: 'Success is liking yourself, liking what you do, and liking how you do it.', author: 'Maya Angelou', category: 'success' },
  { id: 182, text: 'The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.', author: 'Vince Lombardi', category: 'success' },
  { id: 183, text: 'Try not to become a man of success, but rather try to become a man of value.', author: 'Albert Einstein', category: 'success' },
  { id: 184, text: 'The road to success and the road to failure are almost exactly the same.', author: 'Colin R. Davis', category: 'success' },
  { id: 185, text: 'Opportunities don\'t happen. You create them.', author: 'Chris Grosser', category: 'success' },
  { id: 186, text: 'Don\'t let yesterday take up too much of today.', author: 'Will Rogers', category: 'success' },
  { id: 187, text: 'It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.', author: 'Charles Darwin', category: 'success' },
  { id: 188, text: 'Great things are done by a series of small things brought together.', author: 'Vincent Van Gogh', category: 'success' },
  { id: 189, text: 'The secret of success is to do the common thing uncommonly well.', author: 'John D. Rockefeller Jr.', category: 'success' },
  { id: 190, text: 'Success is not in what you have, but who you are.', author: 'Bo Bennett', category: 'success' },
  { id: 191, text: 'The greatest achievement was at first and for a time a dream. The oak sleeps in the acorn.', author: 'James Allen', category: 'success' },
  { id: 192, text: 'A successful man is one who can lay a firm foundation with the bricks others have thrown at him.', author: 'David Brinkley', category: 'success' },
  { id: 193, text: 'Don\'t be distracted by criticism. Remember: the only taste of success some people have is when they take a bite out of you.', author: 'Zig Ziglar', category: 'success' },
  { id: 194, text: 'Success is a lousy teacher. It seduces smart people into thinking they can\'t lose.', author: 'Bill Gates', category: 'success' },
  { id: 195, text: 'Perfection is not attainable, but if we chase perfection we can catch excellence.', author: 'Vince Lombardi', category: 'success' },
  { id: 196, text: 'Success is getting what you want. Happiness is wanting what you get.', author: 'W.P. Kinsella', category: 'success' },
  { id: 197, text: 'Sometimes life knocks you on your ass... get up, dust yourself off, and don\'t let her kick you again.', author: 'Steve Maraboli', category: 'success' },
  { id: 198, text: 'No great thing is created suddenly.', author: 'Epictetus', category: 'success' },
  { id: 199, text: 'The only real mistake is the one from which we learn nothing.', author: 'Henry Ford', category: 'success' },
  { id: 200, text: 'When you reach the end of your rope, tie a knot and hang on.', author: 'Franklin D. Roosevelt', category: 'success' },
  { id: 201, text: 'Always bear in mind that your own resolution to succeed is more important than any one thing.', author: 'Abraham Lincoln', category: 'success' },
  { id: 202, text: 'The harder the battle, the sweeter the victory.', author: 'Les Brown', category: 'success' },
  { id: 203, text: 'Formal education will make you a living; self-education will make you a fortune.', author: 'Jim Rohn', category: 'success' },
  { id: 204, text: 'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.', author: 'Albert Schweitzer', category: 'success' },
  { id: 205, text: 'The secret of success is constancy to purpose.', author: 'Benjamin Disraeli', category: 'success' },
  { id: 206, text: 'Success is not the absence of failure; it\'s the persistence through failure.', author: 'Aisha Tyler', category: 'success' },
  { id: 207, text: 'Success is going from failure to failure without losing your enthusiasm.', author: 'Winston Churchill', category: 'success' },
  { id: 208, text: 'If you really want to do something, you\'ll find a way. If you don\'t, you\'ll find an excuse.', author: 'Jim Rohn', category: 'success' },
  { id: 209, text: 'The distance between insanity and genius is measured only by success.', author: 'Bruce Feirstein', category: 'success' },
  { id: 210, text: 'The mind is everything. What you think you become.', author: 'Buddha', category: 'mindset' },
  { id: 211, text: 'If you want to change the world, start with yourself.', author: 'Mahatma Gandhi', category: 'mindset' },
  { id: 212, text: 'You don\'t have to be great to start, but you have to start to be great.', author: 'Zig Ziglar', category: 'mindset' },
  { id: 213, text: 'The biggest adventure you can take is to live the life of your dreams.', author: 'Oprah Winfrey', category: 'mindset' },
  { id: 214, text: 'Your limitation—it\'s only your imagination.', author: 'Unknown', category: 'mindset' },
  { id: 215, text: 'Great things never come from comfort zones.', author: 'Unknown', category: 'mindset' },
  { id: 216, text: 'Push yourself, because no one else is going to do it for you.', author: 'Unknown', category: 'mindset' },
  { id: 217, text: 'Dream it. Wish it. Do it.', author: 'Unknown', category: 'mindset' },
  { id: 218, text: 'Success doesn\'t just find you. You have to go out and get it.', author: 'Unknown', category: 'mindset' },
  { id: 219, text: 'What we think, we become.', author: 'Buddha', category: 'mindset' },
  { id: 220, text: 'Absorb what is useful. Discard what is not. Add what is uniquely your own.', author: 'Bruce Lee', category: 'mindset' },
  { id: 221, text: 'The only journey is the one within.', author: 'Rainer Maria Rilke', category: 'mindset' },
  { id: 222, text: 'Change your thoughts and you change your world.', author: 'Norman Vincent Peale', category: 'mindset' },
  { id: 223, text: 'The greatest discovery of all time is that a person can change their future by merely changing their attitude.', author: 'Oprah Winfrey', category: 'mindset' },
  { id: 224, text: 'Our mind is a garden, our thoughts are the seeds. We can grow flowers or we can grow weeds.', author: 'Unknown', category: 'mindset' },
  { id: 225, text: 'You are the master of your destiny. You can influence, direct and control your own environment.', author: 'Napoleon Hill', category: 'mindset' },
  { id: 226, text: 'The mind is just like a muscle—the more you exercise it, the stronger it gets.', author: 'Idowu Koyenikan', category: 'mindset' },
  { id: 227, text: 'If you believe it will work out, you\'ll see opportunities. If you believe it won\'t, you will see obstacles.', author: 'Wayne Dyer', category: 'mindset' },
  { id: 228, text: 'A positive attitude causes a chain reaction of positive thoughts, events, and outcomes.', author: 'Wade Boggs', category: 'mindset' },
  { id: 229, text: 'The most powerful relationship you will ever have is the relationship with yourself.', author: 'Steve Maraboli', category: 'mindset' },
  { id: 230, text: 'The biggest room in the world is the room for improvement.', author: 'Helmut Schmidt', category: 'mindset' },
  { id: 231, text: 'The only way to make sense out of change is to plunge into it, move with it, and join the dance.', author: 'Alan Watts', category: 'mindset' },
  { id: 232, text: 'Your attitude, not your aptitude, will determine your altitude.', author: 'Zig Ziglar', category: 'mindset' },
  { id: 233, text: 'The mind is not a vessel to be filled, but a fire to be kindled.', author: 'Plutarch', category: 'mindset' },
  { id: 234, text: 'It is the mark of an educated mind to be able to entertain a thought without accepting it.', author: 'Aristotle', category: 'mindset' },
  { id: 235, text: 'The best way to predict the future is to create it.', author: 'Peter Drucker', category: 'mindset' },
  { id: 236, text: 'Once you change your philosophy, you change your thought process.', author: 'Larry Winget', category: 'mindset' },
  { id: 237, text: 'There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self.', author: 'Ernest Hemingway', category: 'self_development' },
  { id: 238, text: 'One ought, every day at least, to hear a little song, read a good poem, see a fine picture.', author: 'Johann Wolfgang von Goethe', category: 'self_development' },
  { id: 239, text: 'Those who cannot change their minds cannot change anything.', author: 'George Bernard Shaw', category: 'self_development' },
  { id: 240, text: 'A proud man is always looking down on things and people; and, of course, as long as you are looking down, you cannot see something that is above you.', author: 'C.S. Lewis', category: 'self_development' },
  { id: 241, text: 'Make the most of yourself...for that is all there is of you.', author: 'Ralph Waldo Emerson', category: 'self_development' },
  { id: 242, text: 'Always dream and shoot higher than you know you can do.', author: 'William Faulkner', category: 'self_development' },
  { id: 243, text: 'Once we accept our limits, we go beyond them.', author: 'Albert Einstein', category: 'self_development' },
  { id: 244, text: 'No matter who you are, no matter what you did, no matter where you\'ve come from, you can always change, become a better version of yourself.', author: 'Madonna', category: 'self_development' },
  { id: 245, text: 'The curious paradox is that when I accept myself just as I am, then I can change.', author: 'Carl R. Rogers', category: 'self_development' },
  { id: 246, text: 'There is only one corner of the universe you can be certain of improving, and that\'s your own self.', author: 'Aldous Huxley', category: 'self_development' },
  { id: 247, text: 'I like to listen. I have learned a great deal from listening carefully. Most people never listen.', author: 'Ernest Hemingway', category: 'self_development' },
  { id: 248, text: 'A strong man cannot help a weaker unless the weaker is willing to be helped.', author: 'James Allen', category: 'self_development' },
  { id: 249, text: 'You are what you repeatedly do. Excellence, then, is not an act but a habit.', author: 'Aristotle', category: 'self_development' },
  { id: 250, text: 'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.', author: 'Ralph Waldo Emerson', category: 'self_development' },
  { id: 251, text: 'Knowing others is intelligence; knowing yourself is true wisdom.', author: 'Lao Tzu', category: 'self_development' },
  { id: 252, text: 'He who conquers himself is the mightiest warrior.', author: 'Confucius', category: 'self_development' },
  { id: 253, text: 'Be the change that you wish to see in the world.', author: 'Mahatma Gandhi', category: 'self_development' },
  { id: 254, text: 'The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.', author: 'Marcel Proust', category: 'self_development' },
  { id: 255, text: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', author: 'Ralph Waldo Emerson', category: 'self_development' },
  { id: 256, text: 'The battles that count aren\'t the ones for gold medals. The struggles within yourself—that\'s where it\'s at.', author: 'Jesse Owens', category: 'self_development' },
  { id: 257, text: 'Hard work spotlights the character of people.', author: 'Sam Ewing', category: 'self_development' },
  { id: 258, text: 'Self-discipline is the act of making yourself do what you should do.', author: 'Elbert Hubbard', category: 'self_development' },
  { id: 259, text: 'Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.', author: 'Robert Frost', category: 'life_wisdom' },
  { id: 260, text: 'Life is what happens to you while you\'re busy making other plans.', author: 'John Lennon', category: 'life_wisdom' },
  { id: 261, text: 'Twenty years from now you will be more disappointed by the things that you didn\'t do than by the ones you did do.', author: 'Mark Twain', category: 'life_wisdom' },
  { id: 262, text: 'An unexamined life is not worth living.', author: 'Socrates', category: 'life_wisdom' },
  { id: 263, text: 'When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.', author: 'Helen Keller', category: 'life_wisdom' },
  { id: 264, text: 'Everything has beauty, but not everyone can see.', author: 'Confucius', category: 'life_wisdom' },
  { id: 265, text: 'Happiness is not something readymade. It comes from your own actions.', author: 'Dalai Lama', category: 'life_wisdom' },
  { id: 266, text: 'If you\'re offered a seat on a rocket ship, don\'t ask what seat! Just get on.', author: 'Sheryl Sandberg', category: 'life_wisdom' },
  { id: 267, text: 'What\'s money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.', author: 'Bob Dylan', category: 'life_wisdom' },
  { id: 268, text: 'If you look at what you have in life, you\'ll always have more.', author: 'Oprah Winfrey', category: 'life_wisdom' },
  { id: 269, text: 'Remember that not getting what you want is sometimes a wonderful stroke of luck.', author: 'Dalai Lama', category: 'life_wisdom' },
  { id: 270, text: 'You can\'t use up creativity. The more you use, the more you have.', author: 'Maya Angelou', category: 'life_wisdom' },
  { id: 271, text: 'It\'s your place in the world; it\'s your life. Go on and do all you can with it.', author: 'Mae Jemison', category: 'life_wisdom' },
  { id: 272, text: 'When I let go of what I am, I become what I might be.', author: 'Lao Tzu', category: 'life_wisdom' },
  { id: 273, text: 'Life is not measured by the number of breaths we take, but by the moments that take our breath away.', author: 'Maya Angelou', category: 'life_wisdom' },
  { id: 274, text: 'If you want to lift yourself up, lift up someone else.', author: 'Booker T. Washington', category: 'life_wisdom' },
  { id: 275, text: 'When I was 5 years old, my mother always told me that happiness was the key to life.', author: 'John Lennon', category: 'life_wisdom' },
  { id: 276, text: 'Teach thy tongue to say, \'I do not know,\' and thou shalt progress.', author: 'Maimonides', category: 'life_wisdom' },
  { id: 277, text: 'When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.', author: 'Erma Bombeck', category: 'life_wisdom' },
  { id: 278, text: 'First, have a definite, clear practical ideal; a goal, an objective.', author: 'Aristotle', category: 'life_wisdom' },
  { id: 279, text: 'If the wind will not serve, take to the oars.', author: 'Latin Proverb', category: 'life_wisdom' },
  { id: 280, text: 'When you think you can\'t... revisit a previous triumph.', author: 'Jack Canfield', category: 'success' },
  { id: 281, text: 'Sometimes things become possible if we want them bad enough.', author: 'T.S. Eliot', category: 'success' },
  { id: 282, text: 'Courage is facing your fears. Stupidity is fearing nothing.', author: 'Todd Bellemare', category: 'success' },
  { id: 283, text: 'People become successful the minute they decide to.', author: 'Harvey Mackay', category: 'success' },
  { id: 284, text: 'Good things come to those who hustle while they wait.', author: 'Unknown', category: 'success' },
  { id: 285, text: 'Success is predictable.', author: 'Brian Tracy', category: 'success' },
  { id: 286, text: 'Time, patience, and perseverance will accomplish all things.', author: 'Unknown', category: 'success' },
  { id: 287, text: 'To be a winner, all you have to give is all you have.', author: 'Unknown', category: 'success' },
  { id: 288, text: 'The past is over.. .forget it. The future holds hope.. .reach for it.', author: 'Charles R. Swindoll', category: 'success' },
  { id: 289, text: 'Success is more attitude than aptitude.', author: 'Unknown', category: 'success' },
  { id: 290, text: 'There is always a better way.', author: 'Thomas Edison', category: 'success' },
  { id: 291, text: 'The habit of persistence is the habit of victory.', author: 'Herbert Kaufman', category: 'success' },
  { id: 292, text: 'People with goals succeed because they know where they are going.', author: 'Earl Nightingale', category: 'success' },
  { id: 293, text: 'Excellence is not being the best; it is doing your best.', author: 'Unknown', category: 'success' },
  { id: 294, text: 'The size of your success depends on the depth of your desire.', author: 'Unknown', category: 'success' },
  { id: 295, text: 'Don\'t limit your challenges; challenge your limits.', author: 'Unknown', category: 'success' },
  { id: 296, text: 'Life is only what we choose to make it.', author: 'Unknown', category: 'success' },
  { id: 297, text: 'Happiness is the highest level of success.', author: 'Unknown', category: 'success' },
  { id: 298, text: '80% of success is showing up.', author: 'Woody Allen', category: 'success' },
  { id: 299, text: 'He who dares, wins.', author: 'Winston Churchill', category: 'success' },
  { id: 300, text: 'Imagination rules the world.', author: 'Napoleon Bonaparte', category: 'success' },
  { id: 301, text: 'Concentrated thoughts produce desired results.', author: 'Zig Ziglar', category: 'success' },
  { id: 302, text: 'Money never starts an idea; it\'s the idea that starts the money.', author: 'Mark Victor Hansen', category: 'success' },
  { id: 303, text: 'I am not just here to make a living; I am here to make a life.', author: 'Helice Bridges', category: 'success' },
  { id: 304, text: 'The path to success is to take mas- sive determined action.', author: 'Anthony Robbins', category: 'success' },
  { id: 305, text: 'Your dreams minus your doubts equal your true worth.', author: 'Unknown', category: 'success' },
  { id: 306, text: 'The man who said he never had a chance, never took one.', author: 'Unknown', category: 'success' },
  { id: 307, text: 'Success comes to those who dare to begin.', author: 'Unknown', category: 'success' },
  { id: 308, text: 'Dream your wildest dreams and you will live a wild life.', author: 'Unknown', category: 'success' },
  { id: 309, text: 'Your success is only limited by your desire.', author: 'Unknown', category: 'success' },
  { id: 310, text: 'I have failed over and over again. That is why I succeed.', author: 'Michael Jordan', category: 'success' },
  { id: 311, text: 'Believe in yourself and you will be unstoppable.', author: 'Emily Guay', category: 'success' },
  { id: 312, text: 'With each choice you make, you create your life.', author: 'Unknown', category: 'success' },
  { id: 313, text: 'Failure is merely part of the process necessary for success.', author: 'Unknown', category: 'success' },
  { id: 314, text: 'There are no failures in life, only those who give up to soon.', author: 'Unknown', category: 'success' },
  { id: 315, text: 'The door to success is the one marked PUSH.', author: 'Unknown', category: 'success' },
  { id: 316, text: 'Don\'t wish for it.. .work for it!', author: 'Unknown', category: 'success' },
  { id: 317, text: 'Think BIG! You are going to be thinking anyway, so think BIG!', author: 'Donald Trump', category: 'success' },
  { id: 318, text: 'Never let your fears be the boundaries of your dreams.', author: 'Unknown', category: 'success' },
  { id: 319, text: 'Success in the end erases all the mistakes along the way.', author: 'Chinese Proverb', category: 'success' },
  { id: 320, text: 'Winners are ordinary people with extraordinary heart.', author: 'Unknown', category: 'success' },
  { id: 321, text: 'The secret of success is consistency of purpose.', author: 'Benjamin Disraeli', category: 'success' },
  { id: 322, text: 'To conquer without risk is to triumph without glory.', author: 'Unknown', category: 'success' },
  { id: 323, text: 'Life is filled with possibilities.', author: 'Unknown', category: 'success' },
  { id: 324, text: 'Real success is finding your life work in the work that you love.', author: 'David McCullough', category: 'success' },
  { id: 325, text: 'Creativity means believing you have greatness.', author: 'Dr. Wayne D. Dwyer', category: 'success' },
  { id: 326, text: 'Decide what is worthwhile and follow through with it.', author: 'Unknown', category: 'success' },
  { id: 327, text: 'I can\'t believe that God put us on this earth just to be ordinary.', author: 'Lou Holtz', category: 'success' },
  { id: 328, text: 'In the long run, we only hit what we aim at.', author: 'Henry David Thoreau', category: 'success' },
  { id: 329, text: 'Be courageous! Have faith! Go forward.', author: 'Thomas A. Edison', category: 'success' },
  { id: 330, text: 'The actual is limited, the possibilities immense.', author: 'LaMartine', category: 'success' },
  { id: 331, text: 'Stay focused and stay curious. Do what you say you will do.', author: 'Unknown', category: 'success' },
  { id: 332, text: 'This is America.. .we can do anything here!', author: 'Ted Turner', category: 'success' },
  { id: 333, text: 'Nothing great was ever achieved without enthusiasm.', author: 'Ralph Waldo Emerson', category: 'success' },
  { id: 334, text: 'Out of difficulties grow miracles.', author: 'Jean De La Bruyere', category: 'success' },
  { id: 335, text: 'It\'s in your moments of decision that your destiny is shaped.', author: 'Anthony Robbins', category: 'success' },
  { id: 336, text: 'Focus on where you want to go, not where your currently are.', author: 'Unknown', category: 'success' },
  { id: 337, text: 'There are no limitations to any of our dreams.', author: 'Gene Simmons', category: 'success' },
  { id: 338, text: 'The only thing you have to fear is not giving 100%.', author: 'Unknown', category: 'success' },
  { id: 339, text: 'Believe.. .and the magic will follow.', author: 'Unknown', category: 'success' },
  { id: 340, text: 'Our intentions create our reality.', author: 'Dr. Wayne W. Dyer', category: 'success' },
  { id: 341, text: 'Experience tells you what to do. Confidence allows you to do it.', author: 'Stan Smith', category: 'success' },
  { id: 342, text: 'Everything you want is on the other side of fear.', author: 'Jack Canfield', category: 'success' },
  { id: 343, text: 'Your ability will grow to match your dreams.', author: 'Jim Rohn', category: 'success' },
  { id: 344, text: 'Ask yourself, "Am I now ready to make some changes."', author: 'Jack Canfield', category: 'success' },
  { id: 345, text: 'Ask for the business...always!', author: 'Unknown', category: 'success' },
  { id: 346, text: 'All leaders are readers.', author: 'Jim Rohn', category: 'success' },
  { id: 347, text: 'Remember, if you want a different result, do something different.', author: 'Unknown', category: 'success' },
  { id: 348, text: 'Develop the habit of changing your habits.', author: 'Unknown', category: 'success' },
  { id: 349, text: 'Everyday is a gift, that is why it is called the present.', author: 'Unknown', category: 'success' },
  { id: 350, text: 'If I can dream, I can act and if I can act, I can become.', author: 'Poh Yu Khing', category: 'success' },
  { id: 351, text: 'There are no losers in losing, only losers in not wanting to win.', author: 'Jesus M. Trejo', category: 'success' },
  { id: 352, text: 'What have you done today to help you reach your lifelong goals?', author: 'Brian Tracy', category: 'success' },
  { id: 353, text: 'Believe you will be successful and you will.', author: 'Dale Carnegie', category: 'success' },
  { id: 354, text: 'If we always look back, we lose sight of what\'s ahead.', author: 'Justin Sims', category: 'success' },
  { id: 355, text: 'You cannot have everything, but you can try.', author: 'Unknown', category: 'success' },
  { id: 356, text: 'You can never dream too big, but you can think too little.', author: 'Unknown', category: 'success' },
  { id: 357, text: 'Success comes from having dreams that are bigger than your fears.', author: 'Terry Litwiller', category: 'success' },
  { id: 358, text: 'Some things have to be believed to be seen.', author: 'Ralph Hodgson', category: 'success' },
  { id: 359, text: 'We will either find a way or make one.', author: 'Hannibal', category: 'success' },
  { id: 360, text: 'Things do not change - we change.', author: 'Henry David Thoreau', category: 'success' },
  { id: 361, text: 'Take a risk -jump out of your comfort zone!', author: 'Unknown', category: 'success' },
  { id: 362, text: 'Overcome fear by taking action!', author: 'Unknown', category: 'success' },
  { id: 363, text: 'Enthusiasm creates action.', author: 'Unknown', category: 'success' },
  { id: 364, text: 'Habit is either the best of servants or the worst of masters.', author: 'Nathaniel Emmons', category: 'success' },
  { id: 365, text: 'Imagination is more important than knowledge.', author: 'Albert Einstein', category: 'success' },
  { id: 366, text: 'I think, therefore I am.', author: 'Rene Descartes', category: 'success' },
  { id: 367, text: 'Wealth is the product of a man\'s ability to think.', author: 'Ayn Rand', category: 'success' },
  { id: 368, text: 'Success is having your best day everyday.', author: 'Unknown', category: 'success' },
  { id: 369, text: 'Action must be taken at once! There is no time to be lost.', author: 'Miguel Hidalgo', category: 'success' },
  { id: 370, text: 'Ideas shape the course of history.', author: 'John Keynes', category: 'success' },
  { id: 371, text: 'The greater the obstacle, the more glory in achieving it.', author: 'Moliere', category: 'success' },
  { id: 372, text: 'To move the world, we must first move ourselves.', author: 'Socrates', category: 'success' },
  { id: 373, text: 'We must never be afraid to go too far, for success lies just beyond.', author: 'Marcel Proust', category: 'success' },
  { id: 374, text: 'It takes time to be a success, but time is all it takes.', author: 'Unknown', category: 'success' },
  { id: 375, text: 'Where are you going? What are you doing today to get there?', author: 'Unknown', category: 'success' },
  { id: 376, text: 'They can because they think they can.', author: 'Virgil', category: 'success' },
  { id: 377, text: 'Winning starts with beginning.', author: 'Unknown', category: 'success' },
  { id: 378, text: 'The great end of life is not knowledge, but action.', author: 'Thomas Henry Huxley', category: 'success' },
  { id: 379, text: 'If opportunity doesn\'t knock, build a door.', author: 'Unknown', category: 'success' },
  { id: 380, text: 'Failure is never as scary as regret.', author: 'Unknown', category: 'success' },
  { id: 381, text: 'Successful people do what unsuccessful people dare not to.', author: 'Unknown', category: 'success' },
  { id: 382, text: 'I haven\'t failed; I have just found 10,000 ways that didn\'t work.', author: 'Thomas A. Edison', category: 'success' },
  { id: 383, text: 'Real success is not having things, but having victory over yourself.', author: 'Unknown', category: 'success' },
  { id: 384, text: 'The word can\'t is not in the successful man\'s vocabulary.', author: 'Unknown', category: 'success' },
  { id: 385, text: 'Tomorrow is now.', author: 'Elanor Roosevelt', category: 'success' },
  { id: 386, text: 'The secret to success is to be ready when opportunity comes.', author: 'Benjamin Disraeli', category: 'success' },
  { id: 387, text: 'If your life is free of failures, you are not taking enough risks.', author: 'Unknown', category: 'success' },
  { id: 388, text: 'Do extraordinary things; don\'t just dream them.', author: 'Unknown', category: 'success' },
  { id: 389, text: 'The world makes way for a man who knows where he is going.', author: 'Ralph Waldo Emerson', category: 'success' },
  { id: 390, text: 'High expectations are the key to everything.', author: 'Sam Walton', category: 'success' },
  { id: 391, text: 'The only place success comes before work is in the dictionary.', author: 'Donald Kendall', category: 'success' },
  { id: 392, text: 'It is not the mountain we conquer, but ourselves.', author: 'Sir Edmund Hillary', category: 'success' },
  { id: 393, text: 'It takes the hammer of persistence to drive the nail of success.', author: 'John Mason', category: 'success' },
  { id: 394, text: 'He who stops being better, stops being good.', author: 'Oliver Cromwell', category: 'success' },
  { id: 395, text: 'It is what you learn after you know it all that counts.', author: 'John Wooden', category: 'success' },
  { id: 396, text: 'Always do your best. What you plant now, you will harvest later.', author: 'Og Mandino', category: 'success' },
  { id: 397, text: 'Every failure is a step to success.', author: 'Unknown', category: 'success' },
  { id: 398, text: 'Victory belongs to the most persevering.', author: 'Napoleon Bonaparte', category: 'success' },
  { id: 399, text: 'If you can dream it, you can do it.', author: 'Walt Disney', category: 'success' },
  { id: 400, text: 'Picture in your mind a sense of personal destiny!', author: 'Unknown', category: 'success' },
  { id: 401, text: 'Real leaders are ordinary people with extraordinary determination.', author: 'Unknown', category: 'success' },
  { id: 402, text: 'The future belongs to those who believe in their dreams.', author: 'Unknown', category: 'success' },
  { id: 403, text: 'We do not know who we are until we see what we can do.', author: 'Martha Grimes', category: 'success' },
  { id: 404, text: 'Life without risk is not worth living.', author: 'Charles Lindbergh', category: 'success' },
  { id: 405, text: 'Your dreams come true when you act to turn them into realities.', author: 'Unknown', category: 'success' },
  { id: 406, text: 'If you proclaim it and believe it, you will absolutely achieve it.', author: 'Unknown', category: 'success' },
  { id: 407, text: 'Luck is when preparedness meets opportunity.', author: 'Earl Nightingale', category: 'success' },
  { id: 408, text: 'The best way to predict your future is to create it.', author: 'Unknown', category: 'success' },
  { id: 409, text: 'Effort equals results.', author: 'Unknown', category: 'success' },
  { id: 410, text: 'You can change the way you feel by changing the way you think.', author: 'Unknown', category: 'success' },
  { id: 411, text: 'When you believe in yourself and dream big, anything is possible.', author: 'Unknown', category: 'success' },
  { id: 412, text: 'If you continue to work hard, success will follow you.', author: 'Unknown', category: 'success' },
  { id: 413, text: 'Success is to stand in the presence of God unashamed.', author: 'Unknown', category: 'success' },
  { id: 414, text: 'Live your imagination, not your history.', author: 'Stephen Covy', category: 'success' },
  { id: 415, text: 'Ambition is success\'s best friend.', author: 'Unknown', category: 'success' },
  { id: 416, text: 'There is only one way to fail and that is to quit.', author: 'Unknown', category: 'success' },
  { id: 417, text: 'If you want to win, go and meet those who lost.', author: 'Unknown', category: 'success' },
  { id: 418, text: 'Your current conditions do not reflect your ultimate potential.', author: 'Anthony Robbins', category: 'success' },
  { id: 419, text: 'Life is change; growth is optional. Choose wisely.', author: 'Karen Kaiser Clark', category: 'success' },
  { id: 420, text: 'Everything changes when you change.', author: 'Jim Rohn', category: 'success' },
  { id: 421, text: 'The best way to cheer yourself up is to cheer everybody else up.', author: 'Mark Twain', category: 'success' },
  { id: 422, text: 'I will... until.', author: 'Brian Tracy', category: 'success' },
  { id: 423, text: 'I am the captain of my soul. I am the master of my fate.', author: 'William Henley', category: 'success' },
  { id: 424, text: 'The harder I work, the luckier I get.', author: 'James Thurber', category: 'success' },
  { id: 425, text: 'We need men who can dream of things that never were.', author: 'John F. Kennedy', category: 'success' },
  { id: 426, text: 'In the middle of difficulty lies opportunity.', author: 'Albert Einstein', category: 'success' },
  { id: 427, text: 'Achievement comes when you decide to live your possibilities!', author: 'Unknown', category: 'success' },
  { id: 428, text: 'Don\'t think problem, think opportunity.', author: 'Unknown', category: 'success' },
  { id: 429, text: 'Relentlessness and discontent are the first necessities of progress.', author: 'Thomas A. Edison', category: 'success' },
  { id: 430, text: 'Be all that you can be.', author: 'ARMY slogan', category: 'success' },
  { id: 431, text: 'There is no achievement without goals.', author: 'Robert J. McKaine', category: 'success' },
  { id: 432, text: 'Be absolutely determined to enjoy what you do.', author: 'Gerry Sikorski', category: 'success' },
  { id: 433, text: 'Never let the fear of striking out get in your way.', author: 'Babe Ruth', category: 'success' },
  { id: 434, text: 'There is always, always, always something to be thankful for.', author: 'Unknown', category: 'success' },
  { id: 435, text: 'Life is too short to be little.', author: 'Benjamin Disraeli', category: 'success' },
  { id: 436, text: 'This one step, choosing a goal and sticking to it, changes everything.', author: 'Scott Reed', category: 'success' },
  { id: 437, text: 'Never confuse a single defeat with a final defeat.', author: 'F. Scott Fitzgerald', category: 'success' },
  { id: 438, text: 'If at first you don\'t succeed, skydiving is not for you.', author: 'Unknown', category: 'success' },
  { id: 439, text: 'You cannot have any success unless you can accept failure.', author: 'George Cukor', category: 'success' },
  { id: 440, text: 'There is no failure only feedback.', author: 'Robert Allen', category: 'success' },
  { id: 441, text: 'No dreamer is ever too small; no dream is ever too big.', author: 'Unknown', category: 'success' },
  { id: 442, text: 'A thousand mile journey begins with one step.', author: 'Unknown', category: 'success' },
  { id: 443, text: 'The closer one gets to the top, the more one finds that there is no top.', author: 'Nancy Barcus', category: 'success' },
  { id: 444, text: 'Never underestimate the potential and power of the human spirit.', author: 'Unknown', category: 'success' },
  { id: 445, text: 'Great minds have purpose, while others just have wishes.', author: 'Washington Irving', category: 'success' },
  { id: 446, text: 'Learn to listen. Opportunity sometimes knocks very softly.', author: 'Unknown', category: 'success' },
  { id: 447, text: 'Goals that are not written down are just wishes.', author: 'Unknown', category: 'success' },
  { id: 448, text: 'The man who succeeds is the one who seizes the moment.', author: 'Unknown', category: 'success' },
  { id: 449, text: 'Only those who dare to fail greatly can ever achieve greatly.', author: 'Robert Francis Kennedy', category: 'success' },
  { id: 450, text: 'Do not let what you cannot do interfere with what you can do.', author: 'John Wooden', category: 'success' },
  { id: 451, text: 'Let your heart soar as high as it will. Refuse to be average.', author: 'A.W. Tozer', category: 'success' },
  { id: 452, text: 'Challenge yourself all the days of your life.', author: 'Unknown', category: 'success' },
  { id: 453, text: 'Success is a journey, not a destination.', author: 'Ben Sweetland', category: 'success' },
  { id: 454, text: 'Success is not permanent, neither is failure.', author: 'Dell Crossword', category: 'success' },
  { id: 455, text: 'There is no limit to what a man can achieve if he so believes this.', author: 'Thomas J. Vilord', category: 'success' },
  { id: 456, text: 'The more goals you set, the more goals you get.', author: 'Mark Victor Hansen', category: 'success' },
  { id: 457, text: 'Act as though it is impossible to fail.', author: 'Unknown', category: 'success' },
  { id: 458, text: 'For every problem there is an opportunity.', author: 'Unknown', category: 'success' },
  { id: 459, text: 'If God shuts one door, another door opens.', author: 'Irish Proverb', category: 'success' },
  { id: 460, text: 'We must leave our mark on our life while we have it in our power.', author: 'Isak Dinesen', category: 'success' },
  { id: 461, text: 'God\'s gifts put man\'s best dreams to shame.', author: 'Elizabeth Barrett Browning', category: 'success' },
  { id: 462, text: 'We all have the gift of unlimited potential.', author: 'Unknown', category: 'success' },
  { id: 463, text: 'Joy is when anticipation meets action.', author: 'Unknown', category: 'success' },
  { id: 464, text: 'Believing that you can is half the battle.', author: 'Unknown', category: 'success' },
  { id: 465, text: 'Choose your dreams and leave your doubts behind.', author: 'Unknown', category: 'success' },
  { id: 466, text: 'Seek not outside yourself for success lies within.', author: 'Mary Lou Cook', category: 'success' },
  { id: 467, text: 'Embrace life, have confidence in yourself, take action.', author: 'Unknown', category: 'success' },
  { id: 468, text: 'Take a moment to reflect and recharge; its time well spent.', author: 'Unknown', category: 'success' },
  { id: 469, text: 'Nothing is as real as a dream. Have the courage to reach for it.', author: 'Unknown', category: 'success' },
  { id: 470, text: 'If you want a thing done well, do it yourself.', author: 'Napoleon Bonaparte', category: 'success' },
  { id: 471, text: 'Great work is done by people who are not afraid to be great.', author: 'Fernando Flores', category: 'success' },
  { id: 472, text: 'In order to attain the impossible, one must attempt the impossible.', author: 'Miguel de Cervantes', category: 'success' },
  { id: 473, text: 'Hunker down!', author: 'Steve Johnson', category: 'success' },
  { id: 474, text: 'The only real failure is the one from which we learn nothing.', author: 'John Powell', category: 'success' },
  { id: 475, text: 'Whatever you are, be a good one.', author: 'Abraham Lincoln', category: 'success' },
  { id: 476, text: 'Difficulties mastered are opportunities won.', author: 'Winston Churchill', category: 'success' },
  { id: 477, text: 'Today is the best preparation for what tomorrow may bring.', author: 'Unknown', category: 'success' },
  { id: 478, text: 'Tomorrow\'s life is too late - live today.', author: 'Martial', category: 'success' },
  { id: 479, text: 'Stumbling is not the same as falling.', author: 'Portuguese Proverb', category: 'success' },
  { id: 480, text: 'Live life with a fire that can never be extinguished.', author: 'Unknown', category: 'success' },
  { id: 481, text: 'If you can command yourself, you can command the world.', author: 'Chinese Proverb', category: 'success' },
  { id: 482, text: 'Tomorrow belongs to those who have vision today!', author: 'Unknown', category: 'success' },
  { id: 483, text: 'A wise man makes more opportunities than he finds.', author: 'Francis Bacon', category: 'success' },
  { id: 484, text: 'Climb high, climb far, your goal the sky, your aim the stars.', author: 'Unknown', category: 'success' },
  { id: 485, text: 'Success is all in the mind.', author: 'Unknown', category: 'success' },
  { id: 486, text: 'Small opportunities are often the beginning of great enterprises.', author: 'Demosthenes', category: 'success' },
  { id: 487, text: 'Live everyday fully as if it were your last.', author: 'Buddha', category: 'success' },
  { id: 488, text: 'Above all, life should be fun.', author: 'Unknown', category: 'success' },
  { id: 489, text: 'I like the dreams of the future better than the history of the past.', author: 'Thomas Jefferson', category: 'success' },
  { id: 490, text: 'Nothing will come of nothing; we must dare mighty things.', author: 'William Shakespeare', category: 'success' },
  { id: 491, text: 'Do not let the future be held hostage by the past.', author: 'Neal A. Maxwell', category: 'success' },
  { id: 492, text: 'No one knows what he can do until he tries.', author: 'Publilius Syrus', category: 'success' },
  { id: 493, text: 'Success is willing to do what the average person is not willing to do.', author: 'Unknown', category: 'success' },
  { id: 494, text: 'What am I willing to sacrifice to become what I want to become?', author: 'Unknown', category: 'success' },
  { id: 495, text: 'Live with passion.', author: 'Anthony Robbins', category: 'success' },
  { id: 496, text: 'Keep on trying.. .each failure is one step closer to a success.', author: 'Thomas J. Vilord', category: 'success' },
  { id: 497, text: 'Attitude determines altitude.', author: 'Unknown', category: 'success' },
  { id: 498, text: 'The more you prospect, the more you prosper.', author: 'Steve Johnson', category: 'success' },
  { id: 499, text: 'The most important thing is to know that you can do it.', author: 'Robert G. Allen', category: 'success' },
  { id: 500, text: 'I don\'t dream at night, I dream all day; I dream for a living.', author: 'Steven Spielberg', category: 'success' },
  { id: 501, text: 'The real secret to success is enthusiasm.', author: 'Walter Chrysler', category: 'success' },
  { id: 502, text: 'Beware when God lets loose a thinker on this planet.', author: 'Ralph Waldo Emerson', category: 'success' },
  { id: 503, text: 'We cannot become what we want to be by remaining what we are.', author: 'Max Depree', category: 'success' },
  { id: 504, text: 'Success as I see it is a result, not a goal.', author: 'Gustave Flaubert', category: 'success' },
  { id: 505, text: 'A person is led on the path that he truly wants to travel on.', author: 'The Talmud', category: 'success' },
  { id: 506, text: 'Life is either a daring adventure, or nothing at all.', author: 'Helen Keller', category: 'success' },
  { id: 507, text: 'Men are born to succeed, not fail.', author: 'Henry David Thoreau', category: 'success' },
  { id: 508, text: 'Whenever I hear it can\'t be done, I know I am close to success.', author: 'Michael Flatley', category: 'success' },
  { id: 509, text: 'You always pass failure on the way to success.', author: 'Mickey Rooney', category: 'success' },
  { id: 510, text: 'A minute of success pays for years of failure.', author: 'Robert Browning', category: 'success' },
  { id: 511, text: 'To achieve great things, we must dream as well as act.', author: 'Anatole France', category: 'success' },
  { id: 512, text: 'Don\'t go through life, GROW through life.', author: 'Eric Butterworth', category: 'success' },
  { id: 513, text: 'Vision is the art of seeing things that are not yet visible.', author: 'Jonathan Swift', category: 'success' },
  { id: 514, text: 'You must do the things you think you cannot do.', author: 'Elanor Roosevelt', category: 'success' },
  { id: 515, text: 'If at first you don\'t succeed, you are running about average.', author: 'M.H. Alderson', category: 'success' },
  { id: 516, text: 'Most success springs from an obstacle or failure.', author: 'Scott Adams', category: 'success' },
  { id: 517, text: 'One must have strategies to execute dreams.', author: 'Unknown', category: 'success' },
  { id: 518, text: 'It takes twenty years to make an overnight success.', author: 'Eddie Cantor', category: 'success' },
  { id: 519, text: 'It is only as we develop others that we permanently succeed.', author: 'Harvey Samuel Firestone', category: 'success' },
  { id: 520, text: 'Success isn\'t magic or hocus-pocus - its simply learning how to focus.', author: 'Jack Canfield', category: 'success' },
  { id: 521, text: 'A man achieves according to what he believes.', author: 'Unknown', category: 'success' },
  { id: 522, text: 'The secret of success is this: there is no secret to success.', author: 'Elbert Hubbard', category: 'success' },
  { id: 523, text: 'The road to success is always under construction.', author: 'Unknown', category: 'success' },
  { id: 524, text: 'There is plenty of room at the top, but there is no room to sit down.', author: 'Unknown', category: 'success' },
  { id: 525, text: 'None of the secrets of success will work unless you do.', author: 'Unknown', category: 'success' },
  { id: 526, text: 'The secret of success is to never let down and never let up.', author: 'Unknown', category: 'success' },
  { id: 527, text: 'Behind every successful man stands a surprised mother-in-law.', author: 'Hubert H. Humphrey', category: 'success' },
  { id: 528, text: 'Success comes in can\'s. Failures come in cant\'s.', author: 'Unknown', category: 'success' },
  { id: 529, text: 'Intelligence without ambition is like a bird without wings.', author: 'C. Archie Danielson', category: 'success' },
  { id: 530, text: 'I wasn\'t afraid to fail. Something good always comes out of failure.', author: 'Anne Baxter', category: 'success' },
  { id: 531, text: 'Just like a turtle, we only make progress if we stick our neck out.', author: 'James Bryant Conant', category: 'success' },
  { id: 532, text: 'There is no great success without great commitment.', author: 'Unknown', category: 'success' },
  { id: 533, text: 'Doing your best is more important than being the best.', author: 'Unknown', category: 'success' },
  { id: 534, text: 'Between each down and setting sun, set aside some time for fun.', author: 'Unknown', category: 'success' },
  { id: 535, text: 'Wisdom is knowing what to do next; virtue is doing it.', author: 'Unknown', category: 'success' },
  { id: 536, text: 'Take heed: you do not find what you do not seek.', author: 'English Proverb', category: 'success' },
  { id: 537, text: 'People rarely succeed unless they have fun in what they are doing.', author: 'Dale Carnegie', category: 'success' },
  { id: 538, text: 'The only thing ever achieved in life without effort is failure.', author: 'Unknown', category: 'success' },
  { id: 539, text: 'Remove failure as an option.', author: 'Joan Lunden', category: 'success' },
  { id: 540, text: 'What would you attempt if you knew you could not fail?', author: 'Anthony Robbins', category: 'success' },
  { id: 541, text: 'If you are not going to think big, don\'t bother thinking at all.', author: 'Thomas J. Vilord', category: 'success' },
  { id: 542, text: 'A man\'s dreams are an index to his greatness.', author: 'Zadok Rabinowitz', category: 'success' },
  { id: 543, text: 'You can often measure a man by the size of his dreams.', author: 'Robert H. Schuller', category: 'success' },
  { id: 544, text: 'Success consists of getting up just one more time than you fall.', author: 'Oliver Goldsmith', category: 'success' },
  { id: 545, text: 'I want to seize fate by the throat.', author: 'Ludwig van Beethoven', category: 'success' },
  { id: 546, text: 'The very essence of leadership is having vision.', author: 'Father Theodore Hesburg', category: 'success' },
  { id: 547, text: 'Its kind of fun to do the impossible.', author: 'Walt Disney', category: 'success' },
  { id: 548, text: 'God\'s retirement plan is out of this world.', author: 'Unknown', category: 'success' },
  { id: 549, text: 'Past failures are guideposts for future success.', author: 'Unknown', category: 'success' },
  { id: 550, text: 'A positive attitude is a powerful force.. .it can\'t be stopped.', author: 'Unknown', category: 'success' },
  { id: 551, text: 'The one who lacks the courage to start has already finished.', author: 'Unknown', category: 'success' },
  { id: 552, text: 'We are what and where we are because we have first imagined it.', author: 'Donald Curtis', category: 'success' },
  { id: 553, text: 'A quitter never wins and a winner never quits.', author: 'Unknown', category: 'success' },
  { id: 554, text: 'Most of us are just as happy as we make up our minds to be.', author: 'Abraham Lincoln', category: 'success' },
  { id: 555, text: 'The reward for work well done is the opportunity to do more.', author: 'Unknown', category: 'success' },
  { id: 556, text: 'Attitude is a little thing that makes a big difference.', author: 'Unknown', category: 'success' },
  { id: 557, text: 'Hope is not a dream, but a way of making dreams become reality.', author: 'Cardinal Sueneus', category: 'success' },
  { id: 558, text: 'Action, to be effective, must be directed to clearly conceived ends.', author: 'J. Nehru', category: 'success' },
  { id: 559, text: 'Don\'t let failure get you down. Babe Ruth struck out 1,300 times.', author: 'Lou Holtz', category: 'success' },
  { id: 560, text: 'Ideas are the beginning of all achievement.', author: 'Bruce Lee', category: 'success' },
  { id: 561, text: 'May your future be worthy of your dreams.', author: 'Barbara Bush', category: 'success' },
  { id: 562, text: 'Lord, grant that I might always desire more than I can accomplish.', author: 'Michelangelo', category: 'success' },
  { id: 563, text: 'The real risk is doing nothing.', author: 'Denis Waitley', category: 'success' },
  { id: 564, text: 'It\'s always too soon to quit.', author: 'Unknown', category: 'success' },
  { id: 565, text: 'If you think you can win, you can win. Faith is necessary for victory.', author: 'William Hazlitt', category: 'success' },
  { id: 566, text: 'Success is directly proportional to effort.', author: 'Unknown', category: 'success' },
  { id: 567, text: 'Opportunities are multiplied as they are seized.', author: 'Unknown', category: 'success' },
  { id: 568, text: 'Plan to succeed or you have planned to fail.', author: 'Unknown', category: 'success' },
  { id: 569, text: 'When facing a difficult task, act as if you cannot fail.', author: 'Unknown', category: 'success' },
  { id: 570, text: 'Except and expect positive things, and that is what you will receive.', author: 'Lori Hard', category: 'success' },
  { id: 571, text: 'If you don\'t think everyday is a great day, try going without one.', author: 'Jim Evans', category: 'success' },
  { id: 572, text: 'To learn, you have to listen. To improve, you have to try.', author: 'Thomas Jefferson', category: 'success' },
  { id: 573, text: 'The body achieves what the mind believes.', author: 'Unknown', category: 'success' },
  { id: 574, text: 'If you can dream it, you can do it. Your limits are all within yourself.', author: 'Brian Tracy', category: 'success' },
  { id: 575, text: 'Perfection is our goal; excellence will be tolerated.', author: 'Unknown', category: 'success' },
  { id: 576, text: 'Vision plus desire equals reality.', author: 'Unknown', category: 'success' },
  { id: 577, text: 'A winner never stops trying.', author: 'Tom Landry', category: 'success' },
  { id: 578, text: 'Impossibility is an opinion, not a fact.', author: 'Unknown', category: 'success' },
  { id: 579, text: 'The three P\'s of success: Passion, Persistence, and Patience.', author: 'Doug Bronson', category: 'success' },
  { id: 580, text: 'The surest way not to fail is to be determined to succeed.', author: 'Unknown', category: 'success' },
  { id: 581, text: 'If you can\'t find the key to success, pick the lock.', author: 'Unknown', category: 'success' },
  { id: 582, text: 'Set your goals high and don\'t stop until you get there.', author: 'Bo Jackson', category: 'success' },
];
